// Copyright (c) 2007 Nicholas Marriott <nicholas.marriott@gmail.com>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF MIND, USE, DATA OR PROFITS, WHETHER
// IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
// OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

// Special key codes.
#[repr(u64)]
pub(crate) enum keyc {
    // Focus events.
    KEYC_FOCUS_IN = KEYC_BASE,
    KEYC_FOCUS_OUT,

    // "Any" key, used if not found in key table.
    KEYC_ANY,

    // Paste brackets.
    KEYC_PASTE_START,
    KEYC_PASTE_END,

    // Mouse keys.
    KEYC_MOUSE,       // unclassified mouse event
    KEYC_DRAGGING,    // dragging in progress
    KEYC_DOUBLECLICK, // double click complete

    KEYC_MOUSEMOVE_PANE,
    KEYC_MOUSEMOVE_STATUS,
    KEYC_MOUSEMOVE_STATUS_LEFT,
    KEYC_MOUSEMOVE_STATUS_RIGHT,
    KEYC_MOUSEMOVE_STATUS_DEFAULT,
    KEYC_MOUSEMOVE_BORDER,
    KEYC_MOUSEMOVE_SCROLLBAR_UP,
    KEYC_MOUSEMOVE_SCROLLBAR_SLIDER,
    KEYC_MOUSEMOVE_SCROLLBAR_DOWN,
    KEYC_MOUSEMOVE_CONTROL0,
    KEYC_MOUSEMOVE_CONTROL1,
    KEYC_MOUSEMOVE_CONTROL2,
    KEYC_MOUSEMOVE_CONTROL3,
    KEYC_MOUSEMOVE_CONTROL4,
    KEYC_MOUSEMOVE_CONTROL5,
    KEYC_MOUSEMOVE_CONTROL6,
    KEYC_MOUSEMOVE_CONTROL7,
    KEYC_MOUSEMOVE_CONTROL8,
    KEYC_MOUSEMOVE_CONTROL9,

    KEYC_MOUSEDOWN1_PANE,
    KEYC_MOUSEDOWN1_STATUS,
    KEYC_MOUSEDOWN1_STATUS_LEFT,
    KEYC_MOUSEDOWN1_STATUS_RIGHT,
    KEYC_MOUSEDOWN1_STATUS_DEFAULT,
    KEYC_MOUSEDOWN1_BORDER,
    KEYC_MOUSEDOWN1_SCROLLBAR_UP,
    KEYC_MOUSEDOWN1_SCROLLBAR_SLIDER,
    KEYC_MOUSEDOWN1_SCROLLBAR_DOWN,
    KEYC_MOUSEDOWN1_CONTROL0,
    KEYC_MOUSEDOWN1_CONTROL1,
    KEYC_MOUSEDOWN1_CONTROL2,
    KEYC_MOUSEDOWN1_CONTROL3,
    KEYC_MOUSEDOWN1_CONTROL4,
    KEYC_MOUSEDOWN1_CONTROL5,
    KEYC_MOUSEDOWN1_CONTROL6,
    KEYC_MOUSEDOWN1_CONTROL7,
    KEYC_MOUSEDOWN1_CONTROL8,
    KEYC_MOUSEDOWN1_CONTROL9,

    KEYC_MOUSEDOWN2_PANE,
    KEYC_MOUSEDOWN2_STATUS,
    KEYC_MOUSEDOWN2_STATUS_LEFT,
    KEYC_MOUSEDOWN2_STATUS_RIGHT,
    KEYC_MOUSEDOWN2_STATUS_DEFAULT,
    KEYC_MOUSEDOWN2_BORDER,
    KEYC_MOUSEDOWN2_SCROLLBAR_UP,
    KEYC_MOUSEDOWN2_SCROLLBAR_SLIDER,
    KEYC_MOUSEDOWN2_SCROLLBAR_DOWN,
    KEYC_MOUSEDOWN2_CONTROL0,
    KEYC_MOUSEDOWN2_CONTROL1,
    KEYC_MOUSEDOWN2_CONTROL2,
    KEYC_MOUSEDOWN2_CONTROL3,
    KEYC_MOUSEDOWN2_CONTROL4,
    KEYC_MOUSEDOWN2_CONTROL5,
    KEYC_MOUSEDOWN2_CONTROL6,
    KEYC_MOUSEDOWN2_CONTROL7,
    KEYC_MOUSEDOWN2_CONTROL8,
    KEYC_MOUSEDOWN2_CONTROL9,

    KEYC_MOUSEDOWN3_PANE,
    KEYC_MOUSEDOWN3_STATUS,
    KEYC_MOUSEDOWN3_STATUS_LEFT,
    KEYC_MOUSEDOWN3_STATUS_RIGHT,
    KEYC_MOUSEDOWN3_STATUS_DEFAULT,
    KEYC_MOUSEDOWN3_BORDER,
    KEYC_MOUSEDOWN3_SCROLLBAR_UP,
    KEYC_MOUSEDOWN3_SCROLLBAR_SLIDER,
    KEYC_MOUSEDOWN3_SCROLLBAR_DOWN,
    KEYC_MOUSEDOWN3_CONTROL0,
    KEYC_MOUSEDOWN3_CONTROL1,
    KEYC_MOUSEDOWN3_CONTROL2,
    KEYC_MOUSEDOWN3_CONTROL3,
    KEYC_MOUSEDOWN3_CONTROL4,
    KEYC_MOUSEDOWN3_CONTROL5,
    KEYC_MOUSEDOWN3_CONTROL6,
    KEYC_MOUSEDOWN3_CONTROL7,
    KEYC_MOUSEDOWN3_CONTROL8,
    KEYC_MOUSEDOWN3_CONTROL9,

    KEYC_MOUSEDOWN6_PANE,
    KEYC_MOUSEDOWN6_STATUS,
    KEYC_MOUSEDOWN6_STATUS_LEFT,
    KEYC_MOUSEDOWN6_STATUS_RIGHT,
    KEYC_MOUSEDOWN6_STATUS_DEFAULT,
    KEYC_MOUSEDOWN6_BORDER,
    KEYC_MOUSEDOWN6_SCROLLBAR_UP,
    KEYC_MOUSEDOWN6_SCROLLBAR_SLIDER,
    KEYC_MOUSEDOWN6_SCROLLBAR_DOWN,
    KEYC_MOUSEDOWN6_CONTROL0,
    KEYC_MOUSEDOWN6_CONTROL1,
    KEYC_MOUSEDOWN6_CONTROL2,
    KEYC_MOUSEDOWN6_CONTROL3,
    KEYC_MOUSEDOWN6_CONTROL4,
    KEYC_MOUSEDOWN6_CONTROL5,
    KEYC_MOUSEDOWN6_CONTROL6,
    KEYC_MOUSEDOWN6_CONTROL7,
    KEYC_MOUSEDOWN6_CONTROL8,
    KEYC_MOUSEDOWN6_CONTROL9,

    KEYC_MOUSEDOWN7_PANE,
    KEYC_MOUSEDOWN7_STATUS,
    KEYC_MOUSEDOWN7_STATUS_LEFT,
    KEYC_MOUSEDOWN7_STATUS_RIGHT,
    KEYC_MOUSEDOWN7_STATUS_DEFAULT,
    KEYC_MOUSEDOWN7_BORDER,
    KEYC_MOUSEDOWN7_SCROLLBAR_UP,
    KEYC_MOUSEDOWN7_SCROLLBAR_SLIDER,
    KEYC_MOUSEDOWN7_SCROLLBAR_DOWN,
    KEYC_MOUSEDOWN7_CONTROL0,
    KEYC_MOUSEDOWN7_CONTROL1,
    KEYC_MOUSEDOWN7_CONTROL2,
    KEYC_MOUSEDOWN7_CONTROL3,
    KEYC_MOUSEDOWN7_CONTROL4,
    KEYC_MOUSEDOWN7_CONTROL5,
    KEYC_MOUSEDOWN7_CONTROL6,
    KEYC_MOUSEDOWN7_CONTROL7,
    KEYC_MOUSEDOWN7_CONTROL8,
    KEYC_MOUSEDOWN7_CONTROL9,

    KEYC_MOUSEDOWN8_PANE,
    KEYC_MOUSEDOWN8_STATUS,
    KEYC_MOUSEDOWN8_STATUS_LEFT,
    KEYC_MOUSEDOWN8_STATUS_RIGHT,
    KEYC_MOUSEDOWN8_STATUS_DEFAULT,
    KEYC_MOUSEDOWN8_BORDER,
    KEYC_MOUSEDOWN8_SCROLLBAR_UP,
    KEYC_MOUSEDOWN8_SCROLLBAR_SLIDER,
    KEYC_MOUSEDOWN8_SCROLLBAR_DOWN,
    KEYC_MOUSEDOWN8_CONTROL0,
    KEYC_MOUSEDOWN8_CONTROL1,
    KEYC_MOUSEDOWN8_CONTROL2,
    KEYC_MOUSEDOWN8_CONTROL3,
    KEYC_MOUSEDOWN8_CONTROL4,
    KEYC_MOUSEDOWN8_CONTROL5,
    KEYC_MOUSEDOWN8_CONTROL6,
    KEYC_MOUSEDOWN8_CONTROL7,
    KEYC_MOUSEDOWN8_CONTROL8,
    KEYC_MOUSEDOWN8_CONTROL9,

    KEYC_MOUSEDOWN9_PANE,
    KEYC_MOUSEDOWN9_STATUS,
    KEYC_MOUSEDOWN9_STATUS_LEFT,
    KEYC_MOUSEDOWN9_STATUS_RIGHT,
    KEYC_MOUSEDOWN9_STATUS_DEFAULT,
    KEYC_MOUSEDOWN9_BORDER,
    KEYC_MOUSEDOWN9_SCROLLBAR_UP,
    KEYC_MOUSEDOWN9_SCROLLBAR_SLIDER,
    KEYC_MOUSEDOWN9_SCROLLBAR_DOWN,
    KEYC_MOUSEDOWN9_CONTROL0,
    KEYC_MOUSEDOWN9_CONTROL1,
    KEYC_MOUSEDOWN9_CONTROL2,
    KEYC_MOUSEDOWN9_CONTROL3,
    KEYC_MOUSEDOWN9_CONTROL4,
    KEYC_MOUSEDOWN9_CONTROL5,
    KEYC_MOUSEDOWN9_CONTROL6,
    KEYC_MOUSEDOWN9_CONTROL7,
    KEYC_MOUSEDOWN9_CONTROL8,
    KEYC_MOUSEDOWN9_CONTROL9,

    KEYC_MOUSEDOWN10_PANE,
    KEYC_MOUSEDOWN10_STATUS,
    KEYC_MOUSEDOWN10_STATUS_LEFT,
    KEYC_MOUSEDOWN10_STATUS_RIGHT,
    KEYC_MOUSEDOWN10_STATUS_DEFAULT,
    KEYC_MOUSEDOWN10_BORDER,
    KEYC_MOUSEDOWN10_SCROLLBAR_UP,
    KEYC_MOUSEDOWN10_SCROLLBAR_SLIDER,
    KEYC_MOUSEDOWN10_SCROLLBAR_DOWN,
    KEYC_MOUSEDOWN10_CONTROL0,
    KEYC_MOUSEDOWN10_CONTROL1,
    KEYC_MOUSEDOWN10_CONTROL2,
    KEYC_MOUSEDOWN10_CONTROL3,
    KEYC_MOUSEDOWN10_CONTROL4,
    KEYC_MOUSEDOWN10_CONTROL5,
    KEYC_MOUSEDOWN10_CONTROL6,
    KEYC_MOUSEDOWN10_CONTROL7,
    KEYC_MOUSEDOWN10_CONTROL8,
    KEYC_MOUSEDOWN10_CONTROL9,

    KEYC_MOUSEDOWN11_PANE,
    KEYC_MOUSEDOWN11_STATUS,
    KEYC_MOUSEDOWN11_STATUS_LEFT,
    KEYC_MOUSEDOWN11_STATUS_RIGHT,
    KEYC_MOUSEDOWN11_STATUS_DEFAULT,
    KEYC_MOUSEDOWN11_BORDER,
    KEYC_MOUSEDOWN11_SCROLLBAR_UP,
    KEYC_MOUSEDOWN11_SCROLLBAR_SLIDER,
    KEYC_MOUSEDOWN11_SCROLLBAR_DOWN,
    KEYC_MOUSEDOWN11_CONTROL0,
    KEYC_MOUSEDOWN11_CONTROL1,
    KEYC_MOUSEDOWN11_CONTROL2,
    KEYC_MOUSEDOWN11_CONTROL3,
    KEYC_MOUSEDOWN11_CONTROL4,
    KEYC_MOUSEDOWN11_CONTROL5,
    KEYC_MOUSEDOWN11_CONTROL6,
    KEYC_MOUSEDOWN11_CONTROL7,
    KEYC_MOUSEDOWN11_CONTROL8,
    KEYC_MOUSEDOWN11_CONTROL9,

    KEYC_MOUSEUP1_PANE,
    KEYC_MOUSEUP1_STATUS,
    KEYC_MOUSEUP1_STATUS_LEFT,
    KEYC_MOUSEUP1_STATUS_RIGHT,
    KEYC_MOUSEUP1_STATUS_DEFAULT,
    KEYC_MOUSEUP1_BORDER,
    KEYC_MOUSEUP1_SCROLLBAR_UP,
    KEYC_MOUSEUP1_SCROLLBAR_SLIDER,
    KEYC_MOUSEUP1_SCROLLBAR_DOWN,
    KEYC_MOUSEUP1_CONTROL0,
    KEYC_MOUSEUP1_CONTROL1,
    KEYC_MOUSEUP1_CONTROL2,
    KEYC_MOUSEUP1_CONTROL3,
    KEYC_MOUSEUP1_CONTROL4,
    KEYC_MOUSEUP1_CONTROL5,
    KEYC_MOUSEUP1_CONTROL6,
    KEYC_MOUSEUP1_CONTROL7,
    KEYC_MOUSEUP1_CONTROL8,
    KEYC_MOUSEUP1_CONTROL9,

    KEYC_MOUSEUP2_PANE,
    KEYC_MOUSEUP2_STATUS,
    KEYC_MOUSEUP2_STATUS_LEFT,
    KEYC_MOUSEUP2_STATUS_RIGHT,
    KEYC_MOUSEUP2_STATUS_DEFAULT,
    KEYC_MOUSEUP2_BORDER,
    KEYC_MOUSEUP2_SCROLLBAR_UP,
    KEYC_MOUSEUP2_SCROLLBAR_SLIDER,
    KEYC_MOUSEUP2_SCROLLBAR_DOWN,
    KEYC_MOUSEUP2_CONTROL0,
    KEYC_MOUSEUP2_CONTROL1,
    KEYC_MOUSEUP2_CONTROL2,
    KEYC_MOUSEUP2_CONTROL3,
    KEYC_MOUSEUP2_CONTROL4,
    KEYC_MOUSEUP2_CONTROL5,
    KEYC_MOUSEUP2_CONTROL6,
    KEYC_MOUSEUP2_CONTROL7,
    KEYC_MOUSEUP2_CONTROL8,
    KEYC_MOUSEUP2_CONTROL9,

    KEYC_MOUSEUP3_PANE,
    KEYC_MOUSEUP3_STATUS,
    KEYC_MOUSEUP3_STATUS_LEFT,
    KEYC_MOUSEUP3_STATUS_RIGHT,
    KEYC_MOUSEUP3_STATUS_DEFAULT,
    KEYC_MOUSEUP3_BORDER,
    KEYC_MOUSEUP3_SCROLLBAR_UP,
    KEYC_MOUSEUP3_SCROLLBAR_SLIDER,
    KEYC_MOUSEUP3_SCROLLBAR_DOWN,
    KEYC_MOUSEUP3_CONTROL0,
    KEYC_MOUSEUP3_CONTROL1,
    KEYC_MOUSEUP3_CONTROL2,
    KEYC_MOUSEUP3_CONTROL3,
    KEYC_MOUSEUP3_CONTROL4,
    KEYC_MOUSEUP3_CONTROL5,
    KEYC_MOUSEUP3_CONTROL6,
    KEYC_MOUSEUP3_CONTROL7,
    KEYC_MOUSEUP3_CONTROL8,
    KEYC_MOUSEUP3_CONTROL9,

    KEYC_MOUSEUP6_PANE,
    KEYC_MOUSEUP6_STATUS,
    KEYC_MOUSEUP6_STATUS_LEFT,
    KEYC_MOUSEUP6_STATUS_RIGHT,
    KEYC_MOUSEUP6_STATUS_DEFAULT,
    KEYC_MOUSEUP6_BORDER,
    KEYC_MOUSEUP6_SCROLLBAR_UP,
    KEYC_MOUSEUP6_SCROLLBAR_SLIDER,
    KEYC_MOUSEUP6_SCROLLBAR_DOWN,
    KEYC_MOUSEUP6_CONTROL0,
    KEYC_MOUSEUP6_CONTROL1,
    KEYC_MOUSEUP6_CONTROL2,
    KEYC_MOUSEUP6_CONTROL3,
    KEYC_MOUSEUP6_CONTROL4,
    KEYC_MOUSEUP6_CONTROL5,
    KEYC_MOUSEUP6_CONTROL6,
    KEYC_MOUSEUP6_CONTROL7,
    KEYC_MOUSEUP6_CONTROL8,
    KEYC_MOUSEUP6_CONTROL9,

    KEYC_MOUSEUP7_PANE,
    KEYC_MOUSEUP7_STATUS,
    KEYC_MOUSEUP7_STATUS_LEFT,
    KEYC_MOUSEUP7_STATUS_RIGHT,
    KEYC_MOUSEUP7_STATUS_DEFAULT,
    KEYC_MOUSEUP7_BORDER,
    KEYC_MOUSEUP7_SCROLLBAR_UP,
    KEYC_MOUSEUP7_SCROLLBAR_SLIDER,
    KEYC_MOUSEUP7_SCROLLBAR_DOWN,
    KEYC_MOUSEUP7_CONTROL0,
    KEYC_MOUSEUP7_CONTROL1,
    KEYC_MOUSEUP7_CONTROL2,
    KEYC_MOUSEUP7_CONTROL3,
    KEYC_MOUSEUP7_CONTROL4,
    KEYC_MOUSEUP7_CONTROL5,
    KEYC_MOUSEUP7_CONTROL6,
    KEYC_MOUSEUP7_CONTROL7,
    KEYC_MOUSEUP7_CONTROL8,
    KEYC_MOUSEUP7_CONTROL9,

    KEYC_MOUSEUP8_PANE,
    KEYC_MOUSEUP8_STATUS,
    KEYC_MOUSEUP8_STATUS_LEFT,
    KEYC_MOUSEUP8_STATUS_RIGHT,
    KEYC_MOUSEUP8_STATUS_DEFAULT,
    KEYC_MOUSEUP8_BORDER,
    KEYC_MOUSEUP8_SCROLLBAR_UP,
    KEYC_MOUSEUP8_SCROLLBAR_SLIDER,
    KEYC_MOUSEUP8_SCROLLBAR_DOWN,
    KEYC_MOUSEUP8_CONTROL0,
    KEYC_MOUSEUP8_CONTROL1,
    KEYC_MOUSEUP8_CONTROL2,
    KEYC_MOUSEUP8_CONTROL3,
    KEYC_MOUSEUP8_CONTROL4,
    KEYC_MOUSEUP8_CONTROL5,
    KEYC_MOUSEUP8_CONTROL6,
    KEYC_MOUSEUP8_CONTROL7,
    KEYC_MOUSEUP8_CONTROL8,
    KEYC_MOUSEUP8_CONTROL9,

    KEYC_MOUSEUP9_PANE,
    KEYC_MOUSEUP9_STATUS,
    KEYC_MOUSEUP9_STATUS_LEFT,
    KEYC_MOUSEUP9_STATUS_RIGHT,
    KEYC_MOUSEUP9_STATUS_DEFAULT,
    KEYC_MOUSEUP9_BORDER,
    KEYC_MOUSEUP9_SCROLLBAR_UP,
    KEYC_MOUSEUP9_SCROLLBAR_SLIDER,
    KEYC_MOUSEUP9_SCROLLBAR_DOWN,
    KEYC_MOUSEUP9_CONTROL0,
    KEYC_MOUSEUP9_CONTROL1,
    KEYC_MOUSEUP9_CONTROL2,
    KEYC_MOUSEUP9_CONTROL3,
    KEYC_MOUSEUP9_CONTROL4,
    KEYC_MOUSEUP9_CONTROL5,
    KEYC_MOUSEUP9_CONTROL6,
    KEYC_MOUSEUP9_CONTROL7,
    KEYC_MOUSEUP9_CONTROL8,
    KEYC_MOUSEUP9_CONTROL9,

    KEYC_MOUSEUP10_PANE,
    KEYC_MOUSEUP10_STATUS,
    KEYC_MOUSEUP10_STATUS_LEFT,
    KEYC_MOUSEUP10_STATUS_RIGHT,
    KEYC_MOUSEUP10_STATUS_DEFAULT,
    KEYC_MOUSEUP10_BORDER,
    KEYC_MOUSEUP10_SCROLLBAR_UP,
    KEYC_MOUSEUP10_SCROLLBAR_SLIDER,
    KEYC_MOUSEUP10_SCROLLBAR_DOWN,
    KEYC_MOUSEUP10_CONTROL0,
    KEYC_MOUSEUP10_CONTROL1,
    KEYC_MOUSEUP10_CONTROL2,
    KEYC_MOUSEUP10_CONTROL3,
    KEYC_MOUSEUP10_CONTROL4,
    KEYC_MOUSEUP10_CONTROL5,
    KEYC_MOUSEUP10_CONTROL6,
    KEYC_MOUSEUP10_CONTROL7,
    KEYC_MOUSEUP10_CONTROL8,
    KEYC_MOUSEUP10_CONTROL9,

    KEYC_MOUSEUP11_PANE,
    KEYC_MOUSEUP11_STATUS,
    KEYC_MOUSEUP11_STATUS_LEFT,
    KEYC_MOUSEUP11_STATUS_RIGHT,
    KEYC_MOUSEUP11_STATUS_DEFAULT,
    KEYC_MOUSEUP11_BORDER,
    KEYC_MOUSEUP11_SCROLLBAR_UP,
    KEYC_MOUSEUP11_SCROLLBAR_SLIDER,
    KEYC_MOUSEUP11_SCROLLBAR_DOWN,
    KEYC_MOUSEUP11_CONTROL0,
    KEYC_MOUSEUP11_CONTROL1,
    KEYC_MOUSEUP11_CONTROL2,
    KEYC_MOUSEUP11_CONTROL3,
    KEYC_MOUSEUP11_CONTROL4,
    KEYC_MOUSEUP11_CONTROL5,
    KEYC_MOUSEUP11_CONTROL6,
    KEYC_MOUSEUP11_CONTROL7,
    KEYC_MOUSEUP11_CONTROL8,
    KEYC_MOUSEUP11_CONTROL9,

    KEYC_MOUSEDRAG1_PANE,
    KEYC_MOUSEDRAG1_STATUS,
    KEYC_MOUSEDRAG1_STATUS_LEFT,
    KEYC_MOUSEDRAG1_STATUS_RIGHT,
    KEYC_MOUSEDRAG1_STATUS_DEFAULT,
    KEYC_MOUSEDRAG1_BORDER,
    KEYC_MOUSEDRAG1_SCROLLBAR_UP,
    KEYC_MOUSEDRAG1_SCROLLBAR_SLIDER,
    KEYC_MOUSEDRAG1_SCROLLBAR_DOWN,
    KEYC_MOUSEDRAG1_CONTROL0,
    KEYC_MOUSEDRAG1_CONTROL1,
    KEYC_MOUSEDRAG1_CONTROL2,
    KEYC_MOUSEDRAG1_CONTROL3,
    KEYC_MOUSEDRAG1_CONTROL4,
    KEYC_MOUSEDRAG1_CONTROL5,
    KEYC_MOUSEDRAG1_CONTROL6,
    KEYC_MOUSEDRAG1_CONTROL7,
    KEYC_MOUSEDRAG1_CONTROL8,
    KEYC_MOUSEDRAG1_CONTROL9,

    KEYC_MOUSEDRAG2_PANE,
    KEYC_MOUSEDRAG2_STATUS,
    KEYC_MOUSEDRAG2_STATUS_LEFT,
    KEYC_MOUSEDRAG2_STATUS_RIGHT,
    KEYC_MOUSEDRAG2_STATUS_DEFAULT,
    KEYC_MOUSEDRAG2_BORDER,
    KEYC_MOUSEDRAG2_SCROLLBAR_UP,
    KEYC_MOUSEDRAG2_SCROLLBAR_SLIDER,
    KEYC_MOUSEDRAG2_SCROLLBAR_DOWN,
    KEYC_MOUSEDRAG2_CONTROL0,
    KEYC_MOUSEDRAG2_CONTROL1,
    KEYC_MOUSEDRAG2_CONTROL2,
    KEYC_MOUSEDRAG2_CONTROL3,
    KEYC_MOUSEDRAG2_CONTROL4,
    KEYC_MOUSEDRAG2_CONTROL5,
    KEYC_MOUSEDRAG2_CONTROL6,
    KEYC_MOUSEDRAG2_CONTROL7,
    KEYC_MOUSEDRAG2_CONTROL8,
    KEYC_MOUSEDRAG2_CONTROL9,

    KEYC_MOUSEDRAG3_PANE,
    KEYC_MOUSEDRAG3_STATUS,
    KEYC_MOUSEDRAG3_STATUS_LEFT,
    KEYC_MOUSEDRAG3_STATUS_RIGHT,
    KEYC_MOUSEDRAG3_STATUS_DEFAULT,
    KEYC_MOUSEDRAG3_BORDER,
    KEYC_MOUSEDRAG3_SCROLLBAR_UP,
    KEYC_MOUSEDRAG3_SCROLLBAR_SLIDER,
    KEYC_MOUSEDRAG3_SCROLLBAR_DOWN,
    KEYC_MOUSEDRAG3_CONTROL0,
    KEYC_MOUSEDRAG3_CONTROL1,
    KEYC_MOUSEDRAG3_CONTROL2,
    KEYC_MOUSEDRAG3_CONTROL3,
    KEYC_MOUSEDRAG3_CONTROL4,
    KEYC_MOUSEDRAG3_CONTROL5,
    KEYC_MOUSEDRAG3_CONTROL6,
    KEYC_MOUSEDRAG3_CONTROL7,
    KEYC_MOUSEDRAG3_CONTROL8,
    KEYC_MOUSEDRAG3_CONTROL9,

    KEYC_MOUSEDRAG6_PANE,
    KEYC_MOUSEDRAG6_STATUS,
    KEYC_MOUSEDRAG6_STATUS_LEFT,
    KEYC_MOUSEDRAG6_STATUS_RIGHT,
    KEYC_MOUSEDRAG6_STATUS_DEFAULT,
    KEYC_MOUSEDRAG6_BORDER,
    KEYC_MOUSEDRAG6_SCROLLBAR_UP,
    KEYC_MOUSEDRAG6_SCROLLBAR_SLIDER,
    KEYC_MOUSEDRAG6_SCROLLBAR_DOWN,
    KEYC_MOUSEDRAG6_CONTROL0,
    KEYC_MOUSEDRAG6_CONTROL1,
    KEYC_MOUSEDRAG6_CONTROL2,
    KEYC_MOUSEDRAG6_CONTROL3,
    KEYC_MOUSEDRAG6_CONTROL4,
    KEYC_MOUSEDRAG6_CONTROL5,
    KEYC_MOUSEDRAG6_CONTROL6,
    KEYC_MOUSEDRAG6_CONTROL7,
    KEYC_MOUSEDRAG6_CONTROL8,
    KEYC_MOUSEDRAG6_CONTROL9,

    KEYC_MOUSEDRAG7_PANE,
    KEYC_MOUSEDRAG7_STATUS,
    KEYC_MOUSEDRAG7_STATUS_LEFT,
    KEYC_MOUSEDRAG7_STATUS_RIGHT,
    KEYC_MOUSEDRAG7_STATUS_DEFAULT,
    KEYC_MOUSEDRAG7_BORDER,
    KEYC_MOUSEDRAG7_SCROLLBAR_UP,
    KEYC_MOUSEDRAG7_SCROLLBAR_SLIDER,
    KEYC_MOUSEDRAG7_SCROLLBAR_DOWN,
    KEYC_MOUSEDRAG7_CONTROL0,
    KEYC_MOUSEDRAG7_CONTROL1,
    KEYC_MOUSEDRAG7_CONTROL2,
    KEYC_MOUSEDRAG7_CONTROL3,
    KEYC_MOUSEDRAG7_CONTROL4,
    KEYC_MOUSEDRAG7_CONTROL5,
    KEYC_MOUSEDRAG7_CONTROL6,
    KEYC_MOUSEDRAG7_CONTROL7,
    KEYC_MOUSEDRAG7_CONTROL8,
    KEYC_MOUSEDRAG7_CONTROL9,

    KEYC_MOUSEDRAG8_PANE,
    KEYC_MOUSEDRAG8_STATUS,
    KEYC_MOUSEDRAG8_STATUS_LEFT,
    KEYC_MOUSEDRAG8_STATUS_RIGHT,
    KEYC_MOUSEDRAG8_STATUS_DEFAULT,
    KEYC_MOUSEDRAG8_BORDER,
    KEYC_MOUSEDRAG8_SCROLLBAR_UP,
    KEYC_MOUSEDRAG8_SCROLLBAR_SLIDER,
    KEYC_MOUSEDRAG8_SCROLLBAR_DOWN,
    KEYC_MOUSEDRAG8_CONTROL0,
    KEYC_MOUSEDRAG8_CONTROL1,
    KEYC_MOUSEDRAG8_CONTROL2,
    KEYC_MOUSEDRAG8_CONTROL3,
    KEYC_MOUSEDRAG8_CONTROL4,
    KEYC_MOUSEDRAG8_CONTROL5,
    KEYC_MOUSEDRAG8_CONTROL6,
    KEYC_MOUSEDRAG8_CONTROL7,
    KEYC_MOUSEDRAG8_CONTROL8,
    KEYC_MOUSEDRAG8_CONTROL9,

    KEYC_MOUSEDRAG9_PANE,
    KEYC_MOUSEDRAG9_STATUS,
    KEYC_MOUSEDRAG9_STATUS_LEFT,
    KEYC_MOUSEDRAG9_STATUS_RIGHT,
    KEYC_MOUSEDRAG9_STATUS_DEFAULT,
    KEYC_MOUSEDRAG9_BORDER,
    KEYC_MOUSEDRAG9_SCROLLBAR_UP,
    KEYC_MOUSEDRAG9_SCROLLBAR_SLIDER,
    KEYC_MOUSEDRAG9_SCROLLBAR_DOWN,
    KEYC_MOUSEDRAG9_CONTROL0,
    KEYC_MOUSEDRAG9_CONTROL1,
    KEYC_MOUSEDRAG9_CONTROL2,
    KEYC_MOUSEDRAG9_CONTROL3,
    KEYC_MOUSEDRAG9_CONTROL4,
    KEYC_MOUSEDRAG9_CONTROL5,
    KEYC_MOUSEDRAG9_CONTROL6,
    KEYC_MOUSEDRAG9_CONTROL7,
    KEYC_MOUSEDRAG9_CONTROL8,
    KEYC_MOUSEDRAG9_CONTROL9,

    KEYC_MOUSEDRAG10_PANE,
    KEYC_MOUSEDRAG10_STATUS,
    KEYC_MOUSEDRAG10_STATUS_LEFT,
    KEYC_MOUSEDRAG10_STATUS_RIGHT,
    KEYC_MOUSEDRAG10_STATUS_DEFAULT,
    KEYC_MOUSEDRAG10_BORDER,
    KEYC_MOUSEDRAG10_SCROLLBAR_UP,
    KEYC_MOUSEDRAG10_SCROLLBAR_SLIDER,
    KEYC_MOUSEDRAG10_SCROLLBAR_DOWN,
    KEYC_MOUSEDRAG10_CONTROL0,
    KEYC_MOUSEDRAG10_CONTROL1,
    KEYC_MOUSEDRAG10_CONTROL2,
    KEYC_MOUSEDRAG10_CONTROL3,
    KEYC_MOUSEDRAG10_CONTROL4,
    KEYC_MOUSEDRAG10_CONTROL5,
    KEYC_MOUSEDRAG10_CONTROL6,
    KEYC_MOUSEDRAG10_CONTROL7,
    KEYC_MOUSEDRAG10_CONTROL8,
    KEYC_MOUSEDRAG10_CONTROL9,

    KEYC_MOUSEDRAG11_PANE,
    KEYC_MOUSEDRAG11_STATUS,
    KEYC_MOUSEDRAG11_STATUS_LEFT,
    KEYC_MOUSEDRAG11_STATUS_RIGHT,
    KEYC_MOUSEDRAG11_STATUS_DEFAULT,
    KEYC_MOUSEDRAG11_BORDER,
    KEYC_MOUSEDRAG11_SCROLLBAR_UP,
    KEYC_MOUSEDRAG11_SCROLLBAR_SLIDER,
    KEYC_MOUSEDRAG11_SCROLLBAR_DOWN,
    KEYC_MOUSEDRAG11_CONTROL0,
    KEYC_MOUSEDRAG11_CONTROL1,
    KEYC_MOUSEDRAG11_CONTROL2,
    KEYC_MOUSEDRAG11_CONTROL3,
    KEYC_MOUSEDRAG11_CONTROL4,
    KEYC_MOUSEDRAG11_CONTROL5,
    KEYC_MOUSEDRAG11_CONTROL6,
    KEYC_MOUSEDRAG11_CONTROL7,
    KEYC_MOUSEDRAG11_CONTROL8,
    KEYC_MOUSEDRAG11_CONTROL9,

    KEYC_MOUSEDRAGEND1_PANE,
    KEYC_MOUSEDRAGEND1_STATUS,
    KEYC_MOUSEDRAGEND1_STATUS_LEFT,
    KEYC_MOUSEDRAGEND1_STATUS_RIGHT,
    KEYC_MOUSEDRAGEND1_STATUS_DEFAULT,
    KEYC_MOUSEDRAGEND1_BORDER,
    KEYC_MOUSEDRAGEND1_SCROLLBAR_UP,
    KEYC_MOUSEDRAGEND1_SCROLLBAR_SLIDER,
    KEYC_MOUSEDRAGEND1_SCROLLBAR_DOWN,
    KEYC_MOUSEDRAGEND1_CONTROL0,
    KEYC_MOUSEDRAGEND1_CONTROL1,
    KEYC_MOUSEDRAGEND1_CONTROL2,
    KEYC_MOUSEDRAGEND1_CONTROL3,
    KEYC_MOUSEDRAGEND1_CONTROL4,
    KEYC_MOUSEDRAGEND1_CONTROL5,
    KEYC_MOUSEDRAGEND1_CONTROL6,
    KEYC_MOUSEDRAGEND1_CONTROL7,
    KEYC_MOUSEDRAGEND1_CONTROL8,
    KEYC_MOUSEDRAGEND1_CONTROL9,

    KEYC_MOUSEDRAGEND2_PANE,
    KEYC_MOUSEDRAGEND2_STATUS,
    KEYC_MOUSEDRAGEND2_STATUS_LEFT,
    KEYC_MOUSEDRAGEND2_STATUS_RIGHT,
    KEYC_MOUSEDRAGEND2_STATUS_DEFAULT,
    KEYC_MOUSEDRAGEND2_BORDER,
    KEYC_MOUSEDRAGEND2_SCROLLBAR_UP,
    KEYC_MOUSEDRAGEND2_SCROLLBAR_SLIDER,
    KEYC_MOUSEDRAGEND2_SCROLLBAR_DOWN,
    KEYC_MOUSEDRAGEND2_CONTROL0,
    KEYC_MOUSEDRAGEND2_CONTROL1,
    KEYC_MOUSEDRAGEND2_CONTROL2,
    KEYC_MOUSEDRAGEND2_CONTROL3,
    KEYC_MOUSEDRAGEND2_CONTROL4,
    KEYC_MOUSEDRAGEND2_CONTROL5,
    KEYC_MOUSEDRAGEND2_CONTROL6,
    KEYC_MOUSEDRAGEND2_CONTROL7,
    KEYC_MOUSEDRAGEND2_CONTROL8,
    KEYC_MOUSEDRAGEND2_CONTROL9,

    KEYC_MOUSEDRAGEND3_PANE,
    KEYC_MOUSEDRAGEND3_STATUS,
    KEYC_MOUSEDRAGEND3_STATUS_LEFT,
    KEYC_MOUSEDRAGEND3_STATUS_RIGHT,
    KEYC_MOUSEDRAGEND3_STATUS_DEFAULT,
    KEYC_MOUSEDRAGEND3_BORDER,
    KEYC_MOUSEDRAGEND3_SCROLLBAR_UP,
    KEYC_MOUSEDRAGEND3_SCROLLBAR_SLIDER,
    KEYC_MOUSEDRAGEND3_SCROLLBAR_DOWN,
    KEYC_MOUSEDRAGEND3_CONTROL0,
    KEYC_MOUSEDRAGEND3_CONTROL1,
    KEYC_MOUSEDRAGEND3_CONTROL2,
    KEYC_MOUSEDRAGEND3_CONTROL3,
    KEYC_MOUSEDRAGEND3_CONTROL4,
    KEYC_MOUSEDRAGEND3_CONTROL5,
    KEYC_MOUSEDRAGEND3_CONTROL6,
    KEYC_MOUSEDRAGEND3_CONTROL7,
    KEYC_MOUSEDRAGEND3_CONTROL8,
    KEYC_MOUSEDRAGEND3_CONTROL9,

    KEYC_MOUSEDRAGEND6_PANE,
    KEYC_MOUSEDRAGEND6_STATUS,
    KEYC_MOUSEDRAGEND6_STATUS_LEFT,
    KEYC_MOUSEDRAGEND6_STATUS_RIGHT,
    KEYC_MOUSEDRAGEND6_STATUS_DEFAULT,
    KEYC_MOUSEDRAGEND6_BORDER,
    KEYC_MOUSEDRAGEND6_SCROLLBAR_UP,
    KEYC_MOUSEDRAGEND6_SCROLLBAR_SLIDER,
    KEYC_MOUSEDRAGEND6_SCROLLBAR_DOWN,
    KEYC_MOUSEDRAGEND6_CONTROL0,
    KEYC_MOUSEDRAGEND6_CONTROL1,
    KEYC_MOUSEDRAGEND6_CONTROL2,
    KEYC_MOUSEDRAGEND6_CONTROL3,
    KEYC_MOUSEDRAGEND6_CONTROL4,
    KEYC_MOUSEDRAGEND6_CONTROL5,
    KEYC_MOUSEDRAGEND6_CONTROL6,
    KEYC_MOUSEDRAGEND6_CONTROL7,
    KEYC_MOUSEDRAGEND6_CONTROL8,
    KEYC_MOUSEDRAGEND6_CONTROL9,

    KEYC_MOUSEDRAGEND7_PANE,
    KEYC_MOUSEDRAGEND7_STATUS,
    KEYC_MOUSEDRAGEND7_STATUS_LEFT,
    KEYC_MOUSEDRAGEND7_STATUS_RIGHT,
    KEYC_MOUSEDRAGEND7_STATUS_DEFAULT,
    KEYC_MOUSEDRAGEND7_BORDER,
    KEYC_MOUSEDRAGEND7_SCROLLBAR_UP,
    KEYC_MOUSEDRAGEND7_SCROLLBAR_SLIDER,
    KEYC_MOUSEDRAGEND7_SCROLLBAR_DOWN,
    KEYC_MOUSEDRAGEND7_CONTROL0,
    KEYC_MOUSEDRAGEND7_CONTROL1,
    KEYC_MOUSEDRAGEND7_CONTROL2,
    KEYC_MOUSEDRAGEND7_CONTROL3,
    KEYC_MOUSEDRAGEND7_CONTROL4,
    KEYC_MOUSEDRAGEND7_CONTROL5,
    KEYC_MOUSEDRAGEND7_CONTROL6,
    KEYC_MOUSEDRAGEND7_CONTROL7,
    KEYC_MOUSEDRAGEND7_CONTROL8,
    KEYC_MOUSEDRAGEND7_CONTROL9,

    KEYC_MOUSEDRAGEND8_PANE,
    KEYC_MOUSEDRAGEND8_STATUS,
    KEYC_MOUSEDRAGEND8_STATUS_LEFT,
    KEYC_MOUSEDRAGEND8_STATUS_RIGHT,
    KEYC_MOUSEDRAGEND8_STATUS_DEFAULT,
    KEYC_MOUSEDRAGEND8_BORDER,
    KEYC_MOUSEDRAGEND8_SCROLLBAR_UP,
    KEYC_MOUSEDRAGEND8_SCROLLBAR_SLIDER,
    KEYC_MOUSEDRAGEND8_SCROLLBAR_DOWN,
    KEYC_MOUSEDRAGEND8_CONTROL0,
    KEYC_MOUSEDRAGEND8_CONTROL1,
    KEYC_MOUSEDRAGEND8_CONTROL2,
    KEYC_MOUSEDRAGEND8_CONTROL3,
    KEYC_MOUSEDRAGEND8_CONTROL4,
    KEYC_MOUSEDRAGEND8_CONTROL5,
    KEYC_MOUSEDRAGEND8_CONTROL6,
    KEYC_MOUSEDRAGEND8_CONTROL7,
    KEYC_MOUSEDRAGEND8_CONTROL8,
    KEYC_MOUSEDRAGEND8_CONTROL9,

    KEYC_MOUSEDRAGEND9_PANE,
    KEYC_MOUSEDRAGEND9_STATUS,
    KEYC_MOUSEDRAGEND9_STATUS_LEFT,
    KEYC_MOUSEDRAGEND9_STATUS_RIGHT,
    KEYC_MOUSEDRAGEND9_STATUS_DEFAULT,
    KEYC_MOUSEDRAGEND9_BORDER,
    KEYC_MOUSEDRAGEND9_SCROLLBAR_UP,
    KEYC_MOUSEDRAGEND9_SCROLLBAR_SLIDER,
    KEYC_MOUSEDRAGEND9_SCROLLBAR_DOWN,
    KEYC_MOUSEDRAGEND9_CONTROL0,
    KEYC_MOUSEDRAGEND9_CONTROL1,
    KEYC_MOUSEDRAGEND9_CONTROL2,
    KEYC_MOUSEDRAGEND9_CONTROL3,
    KEYC_MOUSEDRAGEND9_CONTROL4,
    KEYC_MOUSEDRAGEND9_CONTROL5,
    KEYC_MOUSEDRAGEND9_CONTROL6,
    KEYC_MOUSEDRAGEND9_CONTROL7,
    KEYC_MOUSEDRAGEND9_CONTROL8,
    KEYC_MOUSEDRAGEND9_CONTROL9,

    KEYC_MOUSEDRAGEND10_PANE,
    KEYC_MOUSEDRAGEND10_STATUS,
    KEYC_MOUSEDRAGEND10_STATUS_LEFT,
    KEYC_MOUSEDRAGEND10_STATUS_RIGHT,
    KEYC_MOUSEDRAGEND10_STATUS_DEFAULT,
    KEYC_MOUSEDRAGEND10_BORDER,
    KEYC_MOUSEDRAGEND10_SCROLLBAR_UP,
    KEYC_MOUSEDRAGEND10_SCROLLBAR_SLIDER,
    KEYC_MOUSEDRAGEND10_SCROLLBAR_DOWN,
    KEYC_MOUSEDRAGEND10_CONTROL0,
    KEYC_MOUSEDRAGEND10_CONTROL1,
    KEYC_MOUSEDRAGEND10_CONTROL2,
    KEYC_MOUSEDRAGEND10_CONTROL3,
    KEYC_MOUSEDRAGEND10_CONTROL4,
    KEYC_MOUSEDRAGEND10_CONTROL5,
    KEYC_MOUSEDRAGEND10_CONTROL6,
    KEYC_MOUSEDRAGEND10_CONTROL7,
    KEYC_MOUSEDRAGEND10_CONTROL8,
    KEYC_MOUSEDRAGEND10_CONTROL9,

    KEYC_MOUSEDRAGEND11_PANE,
    KEYC_MOUSEDRAGEND11_STATUS,
    KEYC_MOUSEDRAGEND11_STATUS_LEFT,
    KEYC_MOUSEDRAGEND11_STATUS_RIGHT,
    KEYC_MOUSEDRAGEND11_STATUS_DEFAULT,
    KEYC_MOUSEDRAGEND11_BORDER,
    KEYC_MOUSEDRAGEND11_SCROLLBAR_UP,
    KEYC_MOUSEDRAGEND11_SCROLLBAR_SLIDER,
    KEYC_MOUSEDRAGEND11_SCROLLBAR_DOWN,
    KEYC_MOUSEDRAGEND11_CONTROL0,
    KEYC_MOUSEDRAGEND11_CONTROL1,
    KEYC_MOUSEDRAGEND11_CONTROL2,
    KEYC_MOUSEDRAGEND11_CONTROL3,
    KEYC_MOUSEDRAGEND11_CONTROL4,
    KEYC_MOUSEDRAGEND11_CONTROL5,
    KEYC_MOUSEDRAGEND11_CONTROL6,
    KEYC_MOUSEDRAGEND11_CONTROL7,
    KEYC_MOUSEDRAGEND11_CONTROL8,
    KEYC_MOUSEDRAGEND11_CONTROL9,

    KEYC_WHEELUP_PANE,
    KEYC_WHEELUP_STATUS,
    KEYC_WHEELUP_STATUS_LEFT,
    KEYC_WHEELUP_STATUS_RIGHT,
    KEYC_WHEELUP_STATUS_DEFAULT,
    KEYC_WHEELUP_BORDER,
    KEYC_WHEELUP_SCROLLBAR_UP,
    KEYC_WHEELUP_SCROLLBAR_SLIDER,
    KEYC_WHEELUP_SCROLLBAR_DOWN,
    KEYC_WHEELUP_CONTROL0,
    KEYC_WHEELUP_CONTROL1,
    KEYC_WHEELUP_CONTROL2,
    KEYC_WHEELUP_CONTROL3,
    KEYC_WHEELUP_CONTROL4,
    KEYC_WHEELUP_CONTROL5,
    KEYC_WHEELUP_CONTROL6,
    KEYC_WHEELUP_CONTROL7,
    KEYC_WHEELUP_CONTROL8,
    KEYC_WHEELUP_CONTROL9,

    KEYC_WHEELDOWN_PANE,
    KEYC_WHEELDOWN_STATUS,
    KEYC_WHEELDOWN_STATUS_LEFT,
    KEYC_WHEELDOWN_STATUS_RIGHT,
    KEYC_WHEELDOWN_STATUS_DEFAULT,
    KEYC_WHEELDOWN_BORDER,
    KEYC_WHEELDOWN_SCROLLBAR_UP,
    KEYC_WHEELDOWN_SCROLLBAR_SLIDER,
    KEYC_WHEELDOWN_SCROLLBAR_DOWN,
    KEYC_WHEELDOWN_CONTROL0,
    KEYC_WHEELDOWN_CONTROL1,
    KEYC_WHEELDOWN_CONTROL2,
    KEYC_WHEELDOWN_CONTROL3,
    KEYC_WHEELDOWN_CONTROL4,
    KEYC_WHEELDOWN_CONTROL5,
    KEYC_WHEELDOWN_CONTROL6,
    KEYC_WHEELDOWN_CONTROL7,
    KEYC_WHEELDOWN_CONTROL8,
    KEYC_WHEELDOWN_CONTROL9,

    KEYC_SECONDCLICK1_PANE,
    KEYC_SECONDCLICK1_STATUS,
    KEYC_SECONDCLICK1_STATUS_LEFT,
    KEYC_SECONDCLICK1_STATUS_RIGHT,
    KEYC_SECONDCLICK1_STATUS_DEFAULT,
    KEYC_SECONDCLICK1_BORDER,
    KEYC_SECONDCLICK1_SCROLLBAR_UP,
    KEYC_SECONDCLICK1_SCROLLBAR_SLIDER,
    KEYC_SECONDCLICK1_SCROLLBAR_DOWN,
    KEYC_SECONDCLICK1_CONTROL0,
    KEYC_SECONDCLICK1_CONTROL1,
    KEYC_SECONDCLICK1_CONTROL2,
    KEYC_SECONDCLICK1_CONTROL3,
    KEYC_SECONDCLICK1_CONTROL4,
    KEYC_SECONDCLICK1_CONTROL5,
    KEYC_SECONDCLICK1_CONTROL6,
    KEYC_SECONDCLICK1_CONTROL7,
    KEYC_SECONDCLICK1_CONTROL8,
    KEYC_SECONDCLICK1_CONTROL9,

    KEYC_SECONDCLICK2_PANE,
    KEYC_SECONDCLICK2_STATUS,
    KEYC_SECONDCLICK2_STATUS_LEFT,
    KEYC_SECONDCLICK2_STATUS_RIGHT,
    KEYC_SECONDCLICK2_STATUS_DEFAULT,
    KEYC_SECONDCLICK2_BORDER,
    KEYC_SECONDCLICK2_SCROLLBAR_UP,
    KEYC_SECONDCLICK2_SCROLLBAR_SLIDER,
    KEYC_SECONDCLICK2_SCROLLBAR_DOWN,
    KEYC_SECONDCLICK2_CONTROL0,
    KEYC_SECONDCLICK2_CONTROL1,
    KEYC_SECONDCLICK2_CONTROL2,
    KEYC_SECONDCLICK2_CONTROL3,
    KEYC_SECONDCLICK2_CONTROL4,
    KEYC_SECONDCLICK2_CONTROL5,
    KEYC_SECONDCLICK2_CONTROL6,
    KEYC_SECONDCLICK2_CONTROL7,
    KEYC_SECONDCLICK2_CONTROL8,
    KEYC_SECONDCLICK2_CONTROL9,

    KEYC_SECONDCLICK3_PANE,
    KEYC_SECONDCLICK3_STATUS,
    KEYC_SECONDCLICK3_STATUS_LEFT,
    KEYC_SECONDCLICK3_STATUS_RIGHT,
    KEYC_SECONDCLICK3_STATUS_DEFAULT,
    KEYC_SECONDCLICK3_BORDER,
    KEYC_SECONDCLICK3_SCROLLBAR_UP,
    KEYC_SECONDCLICK3_SCROLLBAR_SLIDER,
    KEYC_SECONDCLICK3_SCROLLBAR_DOWN,
    KEYC_SECONDCLICK3_CONTROL0,
    KEYC_SECONDCLICK3_CONTROL1,
    KEYC_SECONDCLICK3_CONTROL2,
    KEYC_SECONDCLICK3_CONTROL3,
    KEYC_SECONDCLICK3_CONTROL4,
    KEYC_SECONDCLICK3_CONTROL5,
    KEYC_SECONDCLICK3_CONTROL6,
    KEYC_SECONDCLICK3_CONTROL7,
    KEYC_SECONDCLICK3_CONTROL8,
    KEYC_SECONDCLICK3_CONTROL9,

    KEYC_SECONDCLICK6_PANE,
    KEYC_SECONDCLICK6_STATUS,
    KEYC_SECONDCLICK6_STATUS_LEFT,
    KEYC_SECONDCLICK6_STATUS_RIGHT,
    KEYC_SECONDCLICK6_STATUS_DEFAULT,
    KEYC_SECONDCLICK6_BORDER,
    KEYC_SECONDCLICK6_SCROLLBAR_UP,
    KEYC_SECONDCLICK6_SCROLLBAR_SLIDER,
    KEYC_SECONDCLICK6_SCROLLBAR_DOWN,
    KEYC_SECONDCLICK6_CONTROL0,
    KEYC_SECONDCLICK6_CONTROL1,
    KEYC_SECONDCLICK6_CONTROL2,
    KEYC_SECONDCLICK6_CONTROL3,
    KEYC_SECONDCLICK6_CONTROL4,
    KEYC_SECONDCLICK6_CONTROL5,
    KEYC_SECONDCLICK6_CONTROL6,
    KEYC_SECONDCLICK6_CONTROL7,
    KEYC_SECONDCLICK6_CONTROL8,
    KEYC_SECONDCLICK6_CONTROL9,

    KEYC_SECONDCLICK7_PANE,
    KEYC_SECONDCLICK7_STATUS,
    KEYC_SECONDCLICK7_STATUS_LEFT,
    KEYC_SECONDCLICK7_STATUS_RIGHT,
    KEYC_SECONDCLICK7_STATUS_DEFAULT,
    KEYC_SECONDCLICK7_BORDER,
    KEYC_SECONDCLICK7_SCROLLBAR_UP,
    KEYC_SECONDCLICK7_SCROLLBAR_SLIDER,
    KEYC_SECONDCLICK7_SCROLLBAR_DOWN,
    KEYC_SECONDCLICK7_CONTROL0,
    KEYC_SECONDCLICK7_CONTROL1,
    KEYC_SECONDCLICK7_CONTROL2,
    KEYC_SECONDCLICK7_CONTROL3,
    KEYC_SECONDCLICK7_CONTROL4,
    KEYC_SECONDCLICK7_CONTROL5,
    KEYC_SECONDCLICK7_CONTROL6,
    KEYC_SECONDCLICK7_CONTROL7,
    KEYC_SECONDCLICK7_CONTROL8,
    KEYC_SECONDCLICK7_CONTROL9,

    KEYC_SECONDCLICK8_PANE,
    KEYC_SECONDCLICK8_STATUS,
    KEYC_SECONDCLICK8_STATUS_LEFT,
    KEYC_SECONDCLICK8_STATUS_RIGHT,
    KEYC_SECONDCLICK8_STATUS_DEFAULT,
    KEYC_SECONDCLICK8_BORDER,
    KEYC_SECONDCLICK8_SCROLLBAR_UP,
    KEYC_SECONDCLICK8_SCROLLBAR_SLIDER,
    KEYC_SECONDCLICK8_SCROLLBAR_DOWN,
    KEYC_SECONDCLICK8_CONTROL0,
    KEYC_SECONDCLICK8_CONTROL1,
    KEYC_SECONDCLICK8_CONTROL2,
    KEYC_SECONDCLICK8_CONTROL3,
    KEYC_SECONDCLICK8_CONTROL4,
    KEYC_SECONDCLICK8_CONTROL5,
    KEYC_SECONDCLICK8_CONTROL6,
    KEYC_SECONDCLICK8_CONTROL7,
    KEYC_SECONDCLICK8_CONTROL8,
    KEYC_SECONDCLICK8_CONTROL9,

    KEYC_SECONDCLICK9_PANE,
    KEYC_SECONDCLICK9_STATUS,
    KEYC_SECONDCLICK9_STATUS_LEFT,
    KEYC_SECONDCLICK9_STATUS_RIGHT,
    KEYC_SECONDCLICK9_STATUS_DEFAULT,
    KEYC_SECONDCLICK9_BORDER,
    KEYC_SECONDCLICK9_SCROLLBAR_UP,
    KEYC_SECONDCLICK9_SCROLLBAR_SLIDER,
    KEYC_SECONDCLICK9_SCROLLBAR_DOWN,
    KEYC_SECONDCLICK9_CONTROL0,
    KEYC_SECONDCLICK9_CONTROL1,
    KEYC_SECONDCLICK9_CONTROL2,
    KEYC_SECONDCLICK9_CONTROL3,
    KEYC_SECONDCLICK9_CONTROL4,
    KEYC_SECONDCLICK9_CONTROL5,
    KEYC_SECONDCLICK9_CONTROL6,
    KEYC_SECONDCLICK9_CONTROL7,
    KEYC_SECONDCLICK9_CONTROL8,
    KEYC_SECONDCLICK9_CONTROL9,

    KEYC_SECONDCLICK10_PANE,
    KEYC_SECONDCLICK10_STATUS,
    KEYC_SECONDCLICK10_STATUS_LEFT,
    KEYC_SECONDCLICK10_STATUS_RIGHT,
    KEYC_SECONDCLICK10_STATUS_DEFAULT,
    KEYC_SECONDCLICK10_BORDER,
    KEYC_SECONDCLICK10_SCROLLBAR_UP,
    KEYC_SECONDCLICK10_SCROLLBAR_SLIDER,
    KEYC_SECONDCLICK10_SCROLLBAR_DOWN,
    KEYC_SECONDCLICK10_CONTROL0,
    KEYC_SECONDCLICK10_CONTROL1,
    KEYC_SECONDCLICK10_CONTROL2,
    KEYC_SECONDCLICK10_CONTROL3,
    KEYC_SECONDCLICK10_CONTROL4,
    KEYC_SECONDCLICK10_CONTROL5,
    KEYC_SECONDCLICK10_CONTROL6,
    KEYC_SECONDCLICK10_CONTROL7,
    KEYC_SECONDCLICK10_CONTROL8,
    KEYC_SECONDCLICK10_CONTROL9,

    KEYC_SECONDCLICK11_PANE,
    KEYC_SECONDCLICK11_STATUS,
    KEYC_SECONDCLICK11_STATUS_LEFT,
    KEYC_SECONDCLICK11_STATUS_RIGHT,
    KEYC_SECONDCLICK11_STATUS_DEFAULT,
    KEYC_SECONDCLICK11_BORDER,
    KEYC_SECONDCLICK11_SCROLLBAR_UP,
    KEYC_SECONDCLICK11_SCROLLBAR_SLIDER,
    KEYC_SECONDCLICK11_SCROLLBAR_DOWN,
    KEYC_SECONDCLICK11_CONTROL0,
    KEYC_SECONDCLICK11_CONTROL1,
    KEYC_SECONDCLICK11_CONTROL2,
    KEYC_SECONDCLICK11_CONTROL3,
    KEYC_SECONDCLICK11_CONTROL4,
    KEYC_SECONDCLICK11_CONTROL5,
    KEYC_SECONDCLICK11_CONTROL6,
    KEYC_SECONDCLICK11_CONTROL7,
    KEYC_SECONDCLICK11_CONTROL8,
    KEYC_SECONDCLICK11_CONTROL9,

    KEYC_DOUBLECLICK1_PANE,
    KEYC_DOUBLECLICK1_STATUS,
    KEYC_DOUBLECLICK1_STATUS_LEFT,
    KEYC_DOUBLECLICK1_STATUS_RIGHT,
    KEYC_DOUBLECLICK1_STATUS_DEFAULT,
    KEYC_DOUBLECLICK1_BORDER,
    KEYC_DOUBLECLICK1_SCROLLBAR_UP,
    KEYC_DOUBLECLICK1_SCROLLBAR_SLIDER,
    KEYC_DOUBLECLICK1_SCROLLBAR_DOWN,
    KEYC_DOUBLECLICK1_CONTROL0,
    KEYC_DOUBLECLICK1_CONTROL1,
    KEYC_DOUBLECLICK1_CONTROL2,
    KEYC_DOUBLECLICK1_CONTROL3,
    KEYC_DOUBLECLICK1_CONTROL4,
    KEYC_DOUBLECLICK1_CONTROL5,
    KEYC_DOUBLECLICK1_CONTROL6,
    KEYC_DOUBLECLICK1_CONTROL7,
    KEYC_DOUBLECLICK1_CONTROL8,
    KEYC_DOUBLECLICK1_CONTROL9,

    KEYC_DOUBLECLICK2_PANE,
    KEYC_DOUBLECLICK2_STATUS,
    KEYC_DOUBLECLICK2_STATUS_LEFT,
    KEYC_DOUBLECLICK2_STATUS_RIGHT,
    KEYC_DOUBLECLICK2_STATUS_DEFAULT,
    KEYC_DOUBLECLICK2_BORDER,
    KEYC_DOUBLECLICK2_SCROLLBAR_UP,
    KEYC_DOUBLECLICK2_SCROLLBAR_SLIDER,
    KEYC_DOUBLECLICK2_SCROLLBAR_DOWN,
    KEYC_DOUBLECLICK2_CONTROL0,
    KEYC_DOUBLECLICK2_CONTROL1,
    KEYC_DOUBLECLICK2_CONTROL2,
    KEYC_DOUBLECLICK2_CONTROL3,
    KEYC_DOUBLECLICK2_CONTROL4,
    KEYC_DOUBLECLICK2_CONTROL5,
    KEYC_DOUBLECLICK2_CONTROL6,
    KEYC_DOUBLECLICK2_CONTROL7,
    KEYC_DOUBLECLICK2_CONTROL8,
    KEYC_DOUBLECLICK2_CONTROL9,

    KEYC_DOUBLECLICK3_PANE,
    KEYC_DOUBLECLICK3_STATUS,
    KEYC_DOUBLECLICK3_STATUS_LEFT,
    KEYC_DOUBLECLICK3_STATUS_RIGHT,
    KEYC_DOUBLECLICK3_STATUS_DEFAULT,
    KEYC_DOUBLECLICK3_BORDER,
    KEYC_DOUBLECLICK3_SCROLLBAR_UP,
    KEYC_DOUBLECLICK3_SCROLLBAR_SLIDER,
    KEYC_DOUBLECLICK3_SCROLLBAR_DOWN,
    KEYC_DOUBLECLICK3_CONTROL0,
    KEYC_DOUBLECLICK3_CONTROL1,
    KEYC_DOUBLECLICK3_CONTROL2,
    KEYC_DOUBLECLICK3_CONTROL3,
    KEYC_DOUBLECLICK3_CONTROL4,
    KEYC_DOUBLECLICK3_CONTROL5,
    KEYC_DOUBLECLICK3_CONTROL6,
    KEYC_DOUBLECLICK3_CONTROL7,
    KEYC_DOUBLECLICK3_CONTROL8,
    KEYC_DOUBLECLICK3_CONTROL9,

    KEYC_DOUBLECLICK6_PANE,
    KEYC_DOUBLECLICK6_STATUS,
    KEYC_DOUBLECLICK6_STATUS_LEFT,
    KEYC_DOUBLECLICK6_STATUS_RIGHT,
    KEYC_DOUBLECLICK6_STATUS_DEFAULT,
    KEYC_DOUBLECLICK6_BORDER,
    KEYC_DOUBLECLICK6_SCROLLBAR_UP,
    KEYC_DOUBLECLICK6_SCROLLBAR_SLIDER,
    KEYC_DOUBLECLICK6_SCROLLBAR_DOWN,
    KEYC_DOUBLECLICK6_CONTROL0,
    KEYC_DOUBLECLICK6_CONTROL1,
    KEYC_DOUBLECLICK6_CONTROL2,
    KEYC_DOUBLECLICK6_CONTROL3,
    KEYC_DOUBLECLICK6_CONTROL4,
    KEYC_DOUBLECLICK6_CONTROL5,
    KEYC_DOUBLECLICK6_CONTROL6,
    KEYC_DOUBLECLICK6_CONTROL7,
    KEYC_DOUBLECLICK6_CONTROL8,
    KEYC_DOUBLECLICK6_CONTROL9,

    KEYC_DOUBLECLICK7_PANE,
    KEYC_DOUBLECLICK7_STATUS,
    KEYC_DOUBLECLICK7_STATUS_LEFT,
    KEYC_DOUBLECLICK7_STATUS_RIGHT,
    KEYC_DOUBLECLICK7_STATUS_DEFAULT,
    KEYC_DOUBLECLICK7_BORDER,
    KEYC_DOUBLECLICK7_SCROLLBAR_UP,
    KEYC_DOUBLECLICK7_SCROLLBAR_SLIDER,
    KEYC_DOUBLECLICK7_SCROLLBAR_DOWN,
    KEYC_DOUBLECLICK7_CONTROL0,
    KEYC_DOUBLECLICK7_CONTROL1,
    KEYC_DOUBLECLICK7_CONTROL2,
    KEYC_DOUBLECLICK7_CONTROL3,
    KEYC_DOUBLECLICK7_CONTROL4,
    KEYC_DOUBLECLICK7_CONTROL5,
    KEYC_DOUBLECLICK7_CONTROL6,
    KEYC_DOUBLECLICK7_CONTROL7,
    KEYC_DOUBLECLICK7_CONTROL8,
    KEYC_DOUBLECLICK7_CONTROL9,

    KEYC_DOUBLECLICK8_PANE,
    KEYC_DOUBLECLICK8_STATUS,
    KEYC_DOUBLECLICK8_STATUS_LEFT,
    KEYC_DOUBLECLICK8_STATUS_RIGHT,
    KEYC_DOUBLECLICK8_STATUS_DEFAULT,
    KEYC_DOUBLECLICK8_BORDER,
    KEYC_DOUBLECLICK8_SCROLLBAR_UP,
    KEYC_DOUBLECLICK8_SCROLLBAR_SLIDER,
    KEYC_DOUBLECLICK8_SCROLLBAR_DOWN,
    KEYC_DOUBLECLICK8_CONTROL0,
    KEYC_DOUBLECLICK8_CONTROL1,
    KEYC_DOUBLECLICK8_CONTROL2,
    KEYC_DOUBLECLICK8_CONTROL3,
    KEYC_DOUBLECLICK8_CONTROL4,
    KEYC_DOUBLECLICK8_CONTROL5,
    KEYC_DOUBLECLICK8_CONTROL6,
    KEYC_DOUBLECLICK8_CONTROL7,
    KEYC_DOUBLECLICK8_CONTROL8,
    KEYC_DOUBLECLICK8_CONTROL9,

    KEYC_DOUBLECLICK9_PANE,
    KEYC_DOUBLECLICK9_STATUS,
    KEYC_DOUBLECLICK9_STATUS_LEFT,
    KEYC_DOUBLECLICK9_STATUS_RIGHT,
    KEYC_DOUBLECLICK9_STATUS_DEFAULT,
    KEYC_DOUBLECLICK9_BORDER,
    KEYC_DOUBLECLICK9_SCROLLBAR_UP,
    KEYC_DOUBLECLICK9_SCROLLBAR_SLIDER,
    KEYC_DOUBLECLICK9_SCROLLBAR_DOWN,
    KEYC_DOUBLECLICK9_CONTROL0,
    KEYC_DOUBLECLICK9_CONTROL1,
    KEYC_DOUBLECLICK9_CONTROL2,
    KEYC_DOUBLECLICK9_CONTROL3,
    KEYC_DOUBLECLICK9_CONTROL4,
    KEYC_DOUBLECLICK9_CONTROL5,
    KEYC_DOUBLECLICK9_CONTROL6,
    KEYC_DOUBLECLICK9_CONTROL7,
    KEYC_DOUBLECLICK9_CONTROL8,
    KEYC_DOUBLECLICK9_CONTROL9,

    KEYC_DOUBLECLICK10_PANE,
    KEYC_DOUBLECLICK10_STATUS,
    KEYC_DOUBLECLICK10_STATUS_LEFT,
    KEYC_DOUBLECLICK10_STATUS_RIGHT,
    KEYC_DOUBLECLICK10_STATUS_DEFAULT,
    KEYC_DOUBLECLICK10_BORDER,
    KEYC_DOUBLECLICK10_SCROLLBAR_UP,
    KEYC_DOUBLECLICK10_SCROLLBAR_SLIDER,
    KEYC_DOUBLECLICK10_SCROLLBAR_DOWN,
    KEYC_DOUBLECLICK10_CONTROL0,
    KEYC_DOUBLECLICK10_CONTROL1,
    KEYC_DOUBLECLICK10_CONTROL2,
    KEYC_DOUBLECLICK10_CONTROL3,
    KEYC_DOUBLECLICK10_CONTROL4,
    KEYC_DOUBLECLICK10_CONTROL5,
    KEYC_DOUBLECLICK10_CONTROL6,
    KEYC_DOUBLECLICK10_CONTROL7,
    KEYC_DOUBLECLICK10_CONTROL8,
    KEYC_DOUBLECLICK10_CONTROL9,

    KEYC_DOUBLECLICK11_PANE,
    KEYC_DOUBLECLICK11_STATUS,
    KEYC_DOUBLECLICK11_STATUS_LEFT,
    KEYC_DOUBLECLICK11_STATUS_RIGHT,
    KEYC_DOUBLECLICK11_STATUS_DEFAULT,
    KEYC_DOUBLECLICK11_BORDER,
    KEYC_DOUBLECLICK11_SCROLLBAR_UP,
    KEYC_DOUBLECLICK11_SCROLLBAR_SLIDER,
    KEYC_DOUBLECLICK11_SCROLLBAR_DOWN,
    KEYC_DOUBLECLICK11_CONTROL0,
    KEYC_DOUBLECLICK11_CONTROL1,
    KEYC_DOUBLECLICK11_CONTROL2,
    KEYC_DOUBLECLICK11_CONTROL3,
    KEYC_DOUBLECLICK11_CONTROL4,
    KEYC_DOUBLECLICK11_CONTROL5,
    KEYC_DOUBLECLICK11_CONTROL6,
    KEYC_DOUBLECLICK11_CONTROL7,
    KEYC_DOUBLECLICK11_CONTROL8,
    KEYC_DOUBLECLICK11_CONTROL9,

    KEYC_TRIPLECLICK1_PANE,
    KEYC_TRIPLECLICK1_STATUS,
    KEYC_TRIPLECLICK1_STATUS_LEFT,
    KEYC_TRIPLECLICK1_STATUS_RIGHT,
    KEYC_TRIPLECLICK1_STATUS_DEFAULT,
    KEYC_TRIPLECLICK1_BORDER,
    KEYC_TRIPLECLICK1_SCROLLBAR_UP,
    KEYC_TRIPLECLICK1_SCROLLBAR_SLIDER,
    KEYC_TRIPLECLICK1_SCROLLBAR_DOWN,
    KEYC_TRIPLECLICK1_CONTROL0,
    KEYC_TRIPLECLICK1_CONTROL1,
    KEYC_TRIPLECLICK1_CONTROL2,
    KEYC_TRIPLECLICK1_CONTROL3,
    KEYC_TRIPLECLICK1_CONTROL4,
    KEYC_TRIPLECLICK1_CONTROL5,
    KEYC_TRIPLECLICK1_CONTROL6,
    KEYC_TRIPLECLICK1_CONTROL7,
    KEYC_TRIPLECLICK1_CONTROL8,
    KEYC_TRIPLECLICK1_CONTROL9,

    KEYC_TRIPLECLICK2_PANE,
    KEYC_TRIPLECLICK2_STATUS,
    KEYC_TRIPLECLICK2_STATUS_LEFT,
    KEYC_TRIPLECLICK2_STATUS_RIGHT,
    KEYC_TRIPLECLICK2_STATUS_DEFAULT,
    KEYC_TRIPLECLICK2_BORDER,
    KEYC_TRIPLECLICK2_SCROLLBAR_UP,
    KEYC_TRIPLECLICK2_SCROLLBAR_SLIDER,
    KEYC_TRIPLECLICK2_SCROLLBAR_DOWN,
    KEYC_TRIPLECLICK2_CONTROL0,
    KEYC_TRIPLECLICK2_CONTROL1,
    KEYC_TRIPLECLICK2_CONTROL2,
    KEYC_TRIPLECLICK2_CONTROL3,
    KEYC_TRIPLECLICK2_CONTROL4,
    KEYC_TRIPLECLICK2_CONTROL5,
    KEYC_TRIPLECLICK2_CONTROL6,
    KEYC_TRIPLECLICK2_CONTROL7,
    KEYC_TRIPLECLICK2_CONTROL8,
    KEYC_TRIPLECLICK2_CONTROL9,

    KEYC_TRIPLECLICK3_PANE,
    KEYC_TRIPLECLICK3_STATUS,
    KEYC_TRIPLECLICK3_STATUS_LEFT,
    KEYC_TRIPLECLICK3_STATUS_RIGHT,
    KEYC_TRIPLECLICK3_STATUS_DEFAULT,
    KEYC_TRIPLECLICK3_BORDER,
    KEYC_TRIPLECLICK3_SCROLLBAR_UP,
    KEYC_TRIPLECLICK3_SCROLLBAR_SLIDER,
    KEYC_TRIPLECLICK3_SCROLLBAR_DOWN,
    KEYC_TRIPLECLICK3_CONTROL0,
    KEYC_TRIPLECLICK3_CONTROL1,
    KEYC_TRIPLECLICK3_CONTROL2,
    KEYC_TRIPLECLICK3_CONTROL3,
    KEYC_TRIPLECLICK3_CONTROL4,
    KEYC_TRIPLECLICK3_CONTROL5,
    KEYC_TRIPLECLICK3_CONTROL6,
    KEYC_TRIPLECLICK3_CONTROL7,
    KEYC_TRIPLECLICK3_CONTROL8,
    KEYC_TRIPLECLICK3_CONTROL9,

    KEYC_TRIPLECLICK6_PANE,
    KEYC_TRIPLECLICK6_STATUS,
    KEYC_TRIPLECLICK6_STATUS_LEFT,
    KEYC_TRIPLECLICK6_STATUS_RIGHT,
    KEYC_TRIPLECLICK6_STATUS_DEFAULT,
    KEYC_TRIPLECLICK6_BORDER,
    KEYC_TRIPLECLICK6_SCROLLBAR_UP,
    KEYC_TRIPLECLICK6_SCROLLBAR_SLIDER,
    KEYC_TRIPLECLICK6_SCROLLBAR_DOWN,
    KEYC_TRIPLECLICK6_CONTROL0,
    KEYC_TRIPLECLICK6_CONTROL1,
    KEYC_TRIPLECLICK6_CONTROL2,
    KEYC_TRIPLECLICK6_CONTROL3,
    KEYC_TRIPLECLICK6_CONTROL4,
    KEYC_TRIPLECLICK6_CONTROL5,
    KEYC_TRIPLECLICK6_CONTROL6,
    KEYC_TRIPLECLICK6_CONTROL7,
    KEYC_TRIPLECLICK6_CONTROL8,
    KEYC_TRIPLECLICK6_CONTROL9,

    KEYC_TRIPLECLICK7_PANE,
    KEYC_TRIPLECLICK7_STATUS,
    KEYC_TRIPLECLICK7_STATUS_LEFT,
    KEYC_TRIPLECLICK7_STATUS_RIGHT,
    KEYC_TRIPLECLICK7_STATUS_DEFAULT,
    KEYC_TRIPLECLICK7_BORDER,
    KEYC_TRIPLECLICK7_SCROLLBAR_UP,
    KEYC_TRIPLECLICK7_SCROLLBAR_SLIDER,
    KEYC_TRIPLECLICK7_SCROLLBAR_DOWN,
    KEYC_TRIPLECLICK7_CONTROL0,
    KEYC_TRIPLECLICK7_CONTROL1,
    KEYC_TRIPLECLICK7_CONTROL2,
    KEYC_TRIPLECLICK7_CONTROL3,
    KEYC_TRIPLECLICK7_CONTROL4,
    KEYC_TRIPLECLICK7_CONTROL5,
    KEYC_TRIPLECLICK7_CONTROL6,
    KEYC_TRIPLECLICK7_CONTROL7,
    KEYC_TRIPLECLICK7_CONTROL8,
    KEYC_TRIPLECLICK7_CONTROL9,

    KEYC_TRIPLECLICK8_PANE,
    KEYC_TRIPLECLICK8_STATUS,
    KEYC_TRIPLECLICK8_STATUS_LEFT,
    KEYC_TRIPLECLICK8_STATUS_RIGHT,
    KEYC_TRIPLECLICK8_STATUS_DEFAULT,
    KEYC_TRIPLECLICK8_BORDER,
    KEYC_TRIPLECLICK8_SCROLLBAR_UP,
    KEYC_TRIPLECLICK8_SCROLLBAR_SLIDER,
    KEYC_TRIPLECLICK8_SCROLLBAR_DOWN,
    KEYC_TRIPLECLICK8_CONTROL0,
    KEYC_TRIPLECLICK8_CONTROL1,
    KEYC_TRIPLECLICK8_CONTROL2,
    KEYC_TRIPLECLICK8_CONTROL3,
    KEYC_TRIPLECLICK8_CONTROL4,
    KEYC_TRIPLECLICK8_CONTROL5,
    KEYC_TRIPLECLICK8_CONTROL6,
    KEYC_TRIPLECLICK8_CONTROL7,
    KEYC_TRIPLECLICK8_CONTROL8,
    KEYC_TRIPLECLICK8_CONTROL9,

    KEYC_TRIPLECLICK9_PANE,
    KEYC_TRIPLECLICK9_STATUS,
    KEYC_TRIPLECLICK9_STATUS_LEFT,
    KEYC_TRIPLECLICK9_STATUS_RIGHT,
    KEYC_TRIPLECLICK9_STATUS_DEFAULT,
    KEYC_TRIPLECLICK9_BORDER,
    KEYC_TRIPLECLICK9_SCROLLBAR_UP,
    KEYC_TRIPLECLICK9_SCROLLBAR_SLIDER,
    KEYC_TRIPLECLICK9_SCROLLBAR_DOWN,
    KEYC_TRIPLECLICK9_CONTROL0,
    KEYC_TRIPLECLICK9_CONTROL1,
    KEYC_TRIPLECLICK9_CONTROL2,
    KEYC_TRIPLECLICK9_CONTROL3,
    KEYC_TRIPLECLICK9_CONTROL4,
    KEYC_TRIPLECLICK9_CONTROL5,
    KEYC_TRIPLECLICK9_CONTROL6,
    KEYC_TRIPLECLICK9_CONTROL7,
    KEYC_TRIPLECLICK9_CONTROL8,
    KEYC_TRIPLECLICK9_CONTROL9,

    KEYC_TRIPLECLICK10_PANE,
    KEYC_TRIPLECLICK10_STATUS,
    KEYC_TRIPLECLICK10_STATUS_LEFT,
    KEYC_TRIPLECLICK10_STATUS_RIGHT,
    KEYC_TRIPLECLICK10_STATUS_DEFAULT,
    KEYC_TRIPLECLICK10_BORDER,
    KEYC_TRIPLECLICK10_SCROLLBAR_UP,
    KEYC_TRIPLECLICK10_SCROLLBAR_SLIDER,
    KEYC_TRIPLECLICK10_SCROLLBAR_DOWN,
    KEYC_TRIPLECLICK10_CONTROL0,
    KEYC_TRIPLECLICK10_CONTROL1,
    KEYC_TRIPLECLICK10_CONTROL2,
    KEYC_TRIPLECLICK10_CONTROL3,
    KEYC_TRIPLECLICK10_CONTROL4,
    KEYC_TRIPLECLICK10_CONTROL5,
    KEYC_TRIPLECLICK10_CONTROL6,
    KEYC_TRIPLECLICK10_CONTROL7,
    KEYC_TRIPLECLICK10_CONTROL8,
    KEYC_TRIPLECLICK10_CONTROL9,

    KEYC_TRIPLECLICK11_PANE,
    KEYC_TRIPLECLICK11_STATUS,
    KEYC_TRIPLECLICK11_STATUS_LEFT,
    KEYC_TRIPLECLICK11_STATUS_RIGHT,
    KEYC_TRIPLECLICK11_STATUS_DEFAULT,
    KEYC_TRIPLECLICK11_BORDER,
    KEYC_TRIPLECLICK11_SCROLLBAR_UP,
    KEYC_TRIPLECLICK11_SCROLLBAR_SLIDER,
    KEYC_TRIPLECLICK11_SCROLLBAR_DOWN,
    KEYC_TRIPLECLICK11_CONTROL0,
    KEYC_TRIPLECLICK11_CONTROL1,
    KEYC_TRIPLECLICK11_CONTROL2,
    KEYC_TRIPLECLICK11_CONTROL3,
    KEYC_TRIPLECLICK11_CONTROL4,
    KEYC_TRIPLECLICK11_CONTROL5,
    KEYC_TRIPLECLICK11_CONTROL6,
    KEYC_TRIPLECLICK11_CONTROL7,
    KEYC_TRIPLECLICK11_CONTROL8,
    KEYC_TRIPLECLICK11_CONTROL9,

    // Backspace key.
    KEYC_BSPACE,

    // Function keys.
    KEYC_F1,
    KEYC_F2,
    KEYC_F3,
    KEYC_F4,
    KEYC_F5,
    KEYC_F6,
    KEYC_F7,
    KEYC_F8,
    KEYC_F9,
    KEYC_F10,
    KEYC_F11,
    KEYC_F12,
    KEYC_IC,
    KEYC_DC,
    KEYC_HOME,
    KEYC_END,
    KEYC_NPAGE,
    KEYC_PPAGE,
    KEYC_BTAB,

    // Arrow keys.
    KEYC_UP,
    KEYC_DOWN,
    KEYC_LEFT,
    KEYC_RIGHT,

    // Numeric keypad.
    KEYC_KP_SLASH,
    KEYC_KP_STAR,
    KEYC_KP_MINUS,
    KEYC_KP_SEVEN,
    KEYC_KP_EIGHT,
    KEYC_KP_NINE,
    KEYC_KP_PLUS,
    KEYC_KP_FOUR,
    KEYC_KP_FIVE,
    KEYC_KP_SIX,
    KEYC_KP_ONE,
    KEYC_KP_TWO,
    KEYC_KP_THREE,
    KEYC_KP_ENTER,
    KEYC_KP_ZERO,
    KEYC_KP_PERIOD,

    // Theme reporting (tmux.h:399-401). The C places these between the keypad
    // keys and the mouse keys; this enum keeps the pre-next-3.7 ordering with
    // the mouse keys near the front, so they go at the end instead. The values
    // are internal to the port -- nothing puts a keyc discriminant on the wire
    // -- so only the name/code mapping has to agree with itself.
    KEYC_REPORT_DARK_THEME,
    KEYC_REPORT_LIGHT_THEME,

    // End of special keys.
    KEYC_BASE_END,
}

#[cfg(test)]
mod tests {
    use super::*;

    // Enum discriminant as a `key_code` (u64). Lives inside `mod tests` so it
    // is exempt from the ported-fn-name anti-drift gate.
    fn v(k: keyc) -> u64 {
        k as u64
    }

    // C (tmux.h): `enum keyc { KEYC_FOCUS_IN = KEYC_BASE, ... }`. The first
    // variant is pinned to KEYC_BASE and every later variant increments by one,
    // so the whole special-key block is a single contiguous range. KEYC_BASE is
    // 0x10e000 (highest Unicode PUA base).
    #[test]
    fn focus_in_is_pinned_to_keyc_base() {
        assert_eq!(v(keyc::KEYC_FOCUS_IN), KEYC_BASE);
        assert_eq!(KEYC_BASE, 0x10e000);
    }

    // C order (tmux.h): FOCUS_IN, FOCUS_OUT, ANY, PASTE_START, PASTE_END,
    // MOUSE, DRAGGING, DOUBLECLICK, then the mouse key table starting with
    // MOUSEMOVE_PANE. Verify the leading run is exactly consecutive.
    #[test]
    fn leading_special_keys_are_consecutive() {
        let b = KEYC_BASE;
        assert_eq!(v(keyc::KEYC_FOCUS_OUT), b + 1);
        assert_eq!(v(keyc::KEYC_ANY), b + 2);
        assert_eq!(v(keyc::KEYC_PASTE_START), b + 3);
        assert_eq!(v(keyc::KEYC_PASTE_END), b + 4);
        assert_eq!(v(keyc::KEYC_MOUSE), b + 5);
        assert_eq!(v(keyc::KEYC_DRAGGING), b + 6);
        assert_eq!(v(keyc::KEYC_DOUBLECLICK), b + 7);
        assert_eq!(v(keyc::KEYC_MOUSEMOVE_PANE), b + 8);
    }

    // C: `KEYC_MOUSE_KEYS(t)` emits, for each button, the six locations in a
    // fixed order: PANE, STATUS, STATUS_LEFT, STATUS_RIGHT, STATUS_DEFAULT,
    // BORDER. key-string.c (KEYC_MOUSE_STRING and its inverse parser) maps a
    // mouse key <-> its "MouseDown1Pane" style name purely by this offset from
    // the _PANE base, so the round trip only holds if each location sits at the
    // documented offset. Verify for a MOUSEDOWN and a WHEEL block.
    #[test]
    fn mouse_location_block_is_ordered() {
        let d = v(keyc::KEYC_MOUSEDOWN1_PANE);
        assert_eq!(v(keyc::KEYC_MOUSEDOWN1_STATUS), d + 1);
        assert_eq!(v(keyc::KEYC_MOUSEDOWN1_STATUS_LEFT), d + 2);
        assert_eq!(v(keyc::KEYC_MOUSEDOWN1_STATUS_RIGHT), d + 3);
        assert_eq!(v(keyc::KEYC_MOUSEDOWN1_STATUS_DEFAULT), d + 4);
        assert_eq!(v(keyc::KEYC_MOUSEDOWN1_BORDER), d + 5);

        let w = v(keyc::KEYC_WHEELUP_PANE);
        assert_eq!(v(keyc::KEYC_WHEELUP_STATUS), w + 1);
        assert_eq!(v(keyc::KEYC_WHEELUP_STATUS_LEFT), w + 2);
        assert_eq!(v(keyc::KEYC_WHEELUP_STATUS_RIGHT), w + 3);
        assert_eq!(v(keyc::KEYC_WHEELUP_STATUS_DEFAULT), w + 4);
        assert_eq!(v(keyc::KEYC_WHEELUP_BORDER), w + 5);
        // The thirteen locations next-3.7 added, in tmux.h:177-197 order.
        assert_eq!(v(keyc::KEYC_WHEELUP_SCROLLBAR_UP), w + 6);
        assert_eq!(v(keyc::KEYC_WHEELUP_SCROLLBAR_SLIDER), w + 7);
        assert_eq!(v(keyc::KEYC_WHEELUP_SCROLLBAR_DOWN), w + 8);
        assert_eq!(v(keyc::KEYC_WHEELUP_CONTROL0), w + 9);
        assert_eq!(v(keyc::KEYC_WHEELUP_CONTROL9), w + 18);
    }

    // C: buttons run 1, 2, 3, 6, 7, 8, 9, 10, 11 (4 and 5 are reserved for the
    // wheel), each a full 19-location block (tmux.h:177-197 -- six locations
    // until next-3.7 added the scrollbar arms and CONTROL0-9). Consecutive
    // button blocks are one block apart, and the 3 -> 6 jump is still only one
    // block wide (no gap for the missing 4/5).
    #[test]
    fn mouse_button_blocks_are_one_location_block_apart() {
        let d1 = v(keyc::KEYC_MOUSEDOWN1_PANE);
        assert_eq!(v(keyc::KEYC_MOUSEDOWN2_PANE), d1 + 19);
        assert_eq!(v(keyc::KEYC_MOUSEDOWN3_PANE), d1 + 38);
        assert_eq!(v(keyc::KEYC_MOUSEDOWN6_PANE), d1 + 57);
        assert_eq!(v(keyc::KEYC_MOUSEDOWN7_PANE), d1 + 76);
        assert_eq!(v(keyc::KEYC_MOUSEDOWN8_PANE), d1 + 95);
        assert_eq!(v(keyc::KEYC_MOUSEDOWN9_PANE), d1 + 114);
        assert_eq!(v(keyc::KEYC_MOUSEDOWN10_PANE), d1 + 133);
        assert_eq!(v(keyc::KEYC_MOUSEDOWN11_PANE), d1 + 152);
    }

    // C order of event types: MOUSEMOVE (buttonless, one location block), then
    // the per-button MOUSEDOWN table. So the first MOUSEDOWN block immediately
    // follows the single MOUSEMOVE block.
    #[test]
    fn mousemove_precedes_mousedown_block() {
        assert_eq!(
            v(keyc::KEYC_MOUSEDOWN1_PANE),
            v(keyc::KEYC_MOUSEMOVE_PANE) + 19
        );
    }

    // WHEELUP and WHEELDOWN are buttonless location blocks that follow the
    // DRAGEND table; WHEELDOWN sits directly after WHEELUP (tmux.h order).
    #[test]
    fn wheel_down_follows_wheel_up_block() {
        assert_eq!(v(keyc::KEYC_WHEELDOWN_PANE), v(keyc::KEYC_WHEELUP_PANE) + 19);
    }

    // C (this port's tmux.h era): KEYC_IS_MOUSE(key) is
    //   (key & KEYC_MASK_KEY) >= KEYC_MOUSE && (key & KEYC_MASK_KEY) < KEYC_BSPACE
    // i.e. every enum value from KEYC_MOUSE up to (but excluding) KEYC_BSPACE
    // classifies as a mouse key.
    #[test]
    fn keyc_is_mouse_covers_whole_mouse_range() {
        assert!(KEYC_IS_MOUSE(v(keyc::KEYC_MOUSE)));
        assert!(KEYC_IS_MOUSE(v(keyc::KEYC_DRAGGING)));
        assert!(KEYC_IS_MOUSE(v(keyc::KEYC_DOUBLECLICK)));
        assert!(KEYC_IS_MOUSE(v(keyc::KEYC_MOUSEMOVE_PANE)));
        assert!(KEYC_IS_MOUSE(v(keyc::KEYC_MOUSEDOWN1_PANE)));
        assert!(KEYC_IS_MOUSE(v(keyc::KEYC_MOUSEUP1_PANE)));
        assert!(KEYC_IS_MOUSE(v(keyc::KEYC_WHEELUP_PANE)));
        // Last mouse key, immediately before the KEYC_BSPACE sentinel.
        assert!(KEYC_IS_MOUSE(v(keyc::KEYC_TRIPLECLICK11_BORDER)));
    }

    // The range is half-open: KEYC_PASTE_END sits just below KEYC_MOUSE and
    // KEYC_BSPACE is the exclusive upper bound, so neither is a mouse key.
    // Function/arrow keys and plain ASCII are also excluded.
    #[test]
    fn keyc_is_mouse_excludes_neighbours_and_plain_keys() {
        assert!(!KEYC_IS_MOUSE(v(keyc::KEYC_PASTE_END)));
        assert!(!KEYC_IS_MOUSE(v(keyc::KEYC_BSPACE)));
        assert!(!KEYC_IS_MOUSE(v(keyc::KEYC_F1)));
        assert!(!KEYC_IS_MOUSE(v(keyc::KEYC_UP)));
        assert!(!KEYC_IS_MOUSE(v(keyc::KEYC_KP_PERIOD)));
        assert!(!KEYC_IS_MOUSE(b'a' as u64));
        assert!(!KEYC_IS_MOUSE(0));
    }

    // KEYC_IS_MOUSE masks with KEYC_MASK_KEY first, so modifier and flag bits
    // never change the classification (tmux.h).
    #[test]
    fn keyc_is_mouse_ignores_modifier_and_flag_bits() {
        let k = v(keyc::KEYC_MOUSEDOWN1_PANE);
        assert!(KEYC_IS_MOUSE(k | KEYC_CTRL | KEYC_META | KEYC_SHIFT));
        assert!(KEYC_IS_MOUSE(k | KEYC_MASK_FLAGS));
        // A non-mouse key stays non-mouse even with modifiers applied.
        assert!(!KEYC_IS_MOUSE(v(keyc::KEYC_F1) | KEYC_CTRL));
    }

    // C order: the mouse table ends at TRIPLECLICK11_BORDER, then KEYC_BSPACE,
    // then the function keys F1.. immediately after it.
    #[test]
    fn function_keys_follow_bspace_after_mouse_table() {
        assert!(v(keyc::KEYC_BSPACE) > v(keyc::KEYC_TRIPLECLICK11_BORDER));
        assert_eq!(v(keyc::KEYC_F1), v(keyc::KEYC_BSPACE) + 1);
        assert_eq!(v(keyc::KEYC_F2), v(keyc::KEYC_F1) + 1);
    }

    // KEYC_BASE_END is the sentinel terminating the special-key enum, so it
    // must sit above every real key in it. It used to be asserted as
    // KP_PERIOD + 1, but that only held while the keypad keys happened to be
    // declared last; the C does not have that property either (tmux.h:394-405
    // puts the theme keys and the whole mouse block after KP_PERIOD). The
    // invariant that actually matters is the one checked here: the sentinel is
    // one past the last declared key and above every family's terminal member.
    #[test]
    fn base_end_is_the_final_sentinel() {
        assert_eq!(v(keyc::KEYC_BASE_END), v(keyc::KEYC_REPORT_LIGHT_THEME) + 1);
        assert!(v(keyc::KEYC_BASE_END) > v(keyc::KEYC_KP_PERIOD));
        assert!(v(keyc::KEYC_BASE_END) > v(keyc::KEYC_TRIPLECLICK11_BORDER));
        assert!(v(keyc::KEYC_BASE_END) > v(keyc::KEYC_F12));
        assert!(v(keyc::KEYC_BASE_END) > KEYC_BASE);
    }

    // The two theme-reporting keys are real members of the special-key range,
    // so KEYC_IS_MOUSE must not claim them and they must fall inside the
    // KEYC_BASE..KEYC_BASE_END window the ignore-guard in input_key tests.
    #[test]
    fn theme_report_keys_are_special_but_not_mouse() {
        for k in [
            v(keyc::KEYC_REPORT_DARK_THEME),
            v(keyc::KEYC_REPORT_LIGHT_THEME),
        ] {
            assert!(k >= KEYC_BASE && k < v(keyc::KEYC_BASE_END));
            assert!(!KEYC_IS_MOUSE(k));
        }
        assert_eq!(
            v(keyc::KEYC_REPORT_LIGHT_THEME),
            v(keyc::KEYC_REPORT_DARK_THEME) + 1
        );
    }

    // The six-location block ordering (PANE, STATUS, STATUS_LEFT, STATUS_RIGHT,
    // STATUS_DEFAULT, BORDER) must hold for EVERY event family, since the
    // key-string.c mouse name parser resolves a location purely by its offset
    // from the family's _PANE base. Check MOUSEUP / MOUSEDRAG / MOUSEDRAGEND.
    #[test]
    fn up_drag_dragend_location_blocks_are_ordered() {
        for base in [
            v(keyc::KEYC_MOUSEUP1_PANE),
            v(keyc::KEYC_MOUSEDRAG1_PANE),
            v(keyc::KEYC_MOUSEDRAGEND1_PANE),
        ] {
            assert_eq!(base + 1, base + 1); // PANE..BORDER contiguous below
        }
        let u = v(keyc::KEYC_MOUSEUP1_PANE);
        assert_eq!(v(keyc::KEYC_MOUSEUP1_STATUS), u + 1);
        assert_eq!(v(keyc::KEYC_MOUSEUP1_STATUS_LEFT), u + 2);
        assert_eq!(v(keyc::KEYC_MOUSEUP1_STATUS_RIGHT), u + 3);
        assert_eq!(v(keyc::KEYC_MOUSEUP1_STATUS_DEFAULT), u + 4);
        assert_eq!(v(keyc::KEYC_MOUSEUP1_BORDER), u + 5);

        let dr = v(keyc::KEYC_MOUSEDRAG1_PANE);
        assert_eq!(v(keyc::KEYC_MOUSEDRAG1_STATUS_DEFAULT), dr + 4);
        assert_eq!(v(keyc::KEYC_MOUSEDRAG1_BORDER), dr + 5);

        let de = v(keyc::KEYC_MOUSEDRAGEND1_PANE);
        assert_eq!(v(keyc::KEYC_MOUSEDRAGEND1_STATUS_DEFAULT), de + 4);
        assert_eq!(v(keyc::KEYC_MOUSEDRAGEND1_BORDER), de + 5);
    }

    // The click families (SECONDCLICK, DOUBLECLICK, TRIPLECLICK) keep the same
    // six-location block layout for their first button.
    #[test]
    fn click_family_location_blocks_are_ordered() {
        for base in [
            v(keyc::KEYC_SECONDCLICK1_PANE),
            v(keyc::KEYC_DOUBLECLICK1_PANE),
            v(keyc::KEYC_TRIPLECLICK1_PANE),
        ] {
            // BORDER is exactly 5 past PANE for each family's button 1.
            // (verified per-family below with the concrete enum names)
            let _ = base;
        }
        let s = v(keyc::KEYC_SECONDCLICK1_PANE);
        assert_eq!(v(keyc::KEYC_SECONDCLICK1_BORDER), s + 5);
        let d = v(keyc::KEYC_DOUBLECLICK1_PANE);
        assert_eq!(v(keyc::KEYC_DOUBLECLICK1_BORDER), d + 5);
        let t = v(keyc::KEYC_TRIPLECLICK1_PANE);
        assert_eq!(v(keyc::KEYC_TRIPLECLICK1_BORDER), t + 5);
    }

    // The button numbering skips 4 and 5 (reserved for the wheel) for the
    // MOUSEUP and MOUSEDRAG families too, so button blocks are a flat one
    // location block (19) apart with no gap at the 3 -> 6 transition.
    #[test]
    fn up_and_drag_button_blocks_are_one_location_block_apart() {
        let u = v(keyc::KEYC_MOUSEUP1_PANE);
        assert_eq!(v(keyc::KEYC_MOUSEUP2_PANE), u + 19);
        assert_eq!(v(keyc::KEYC_MOUSEUP3_PANE), u + 38);
        assert_eq!(v(keyc::KEYC_MOUSEUP6_PANE), u + 57);
        assert_eq!(v(keyc::KEYC_MOUSEUP11_PANE), u + 152);

        let d = v(keyc::KEYC_MOUSEDRAG1_PANE);
        assert_eq!(v(keyc::KEYC_MOUSEDRAG3_PANE), d + 38);
        assert_eq!(v(keyc::KEYC_MOUSEDRAG6_PANE), d + 57);
        assert_eq!(v(keyc::KEYC_MOUSEDRAG11_PANE), d + 152);
    }

    // Event-family ordering (tmux.h): MOUSEMOVE, MOUSEDOWN, MOUSEUP, MOUSEDRAG,
    // MOUSEDRAGEND, WHEELUP, WHEELDOWN, SECONDCLICK, DOUBLECLICK, TRIPLECLICK.
    // Each per-button family spans 9 buttons * 19 locations = 171; the
    // buttonless WHEEL families span 19. Verify the chain is monotonic.
    #[test]
    fn event_family_starts_are_monotonic() {
        let starts = [
            v(keyc::KEYC_MOUSEMOVE_PANE),
            v(keyc::KEYC_MOUSEDOWN1_PANE),
            v(keyc::KEYC_MOUSEUP1_PANE),
            v(keyc::KEYC_MOUSEDRAG1_PANE),
            v(keyc::KEYC_MOUSEDRAGEND1_PANE),
            v(keyc::KEYC_WHEELUP_PANE),
            v(keyc::KEYC_WHEELDOWN_PANE),
            v(keyc::KEYC_SECONDCLICK1_PANE),
            v(keyc::KEYC_DOUBLECLICK1_PANE),
            v(keyc::KEYC_TRIPLECLICK1_PANE),
        ];
        assert!(starts.windows(2).all(|w| w[0] < w[1]), "families must be in order");
        // The three per-button families before the wheels are each 171 wide.
        assert_eq!(v(keyc::KEYC_MOUSEUP1_PANE), v(keyc::KEYC_MOUSEDOWN1_PANE) + 171);
        assert_eq!(v(keyc::KEYC_MOUSEDRAG1_PANE), v(keyc::KEYC_MOUSEUP1_PANE) + 171);
        // WHEELUP directly follows the DRAGEND family (171 wide).
        assert_eq!(v(keyc::KEYC_WHEELUP_PANE), v(keyc::KEYC_MOUSEDRAGEND1_PANE) + 171);
    }

    // The TRIPLECLICK family is the last mouse family; its final entry sits
    // immediately before KEYC_BSPACE (the exclusive KEYC_IS_MOUSE upper bound).
    #[test]
    fn tripleclick_is_last_mouse_family_before_bspace() {
        assert_eq!(v(keyc::KEYC_BSPACE), v(keyc::KEYC_TRIPLECLICK11_CONTROL9) + 1);
        // SECONDCLICK precedes DOUBLECLICK precedes TRIPLECLICK, each 171 wide.
        assert_eq!(
            v(keyc::KEYC_DOUBLECLICK1_PANE),
            v(keyc::KEYC_SECONDCLICK1_PANE) + 171
        );
        assert_eq!(
            v(keyc::KEYC_TRIPLECLICK1_PANE),
            v(keyc::KEYC_DOUBLECLICK1_PANE) + 171
        );
    }
}
