$TM show-options -gv status-style
$TM show-options -gv mode-style
$TM show-options -wgv copy-mode-mark-style
$TM show-options -wgv copy-mode-match-style
$TM show-options -wgv copy-mode-current-match-style
$TM show-options -gv menu-style
$TM show-options -gv menu-border-style
$TM show-options -gv menu-selected-style
$TM show-options -gv message-style
$TM show-options -gv message-command-style
$TM show-options -wgv pane-border-style
$TM show-options -wgv pane-active-border-style
$TM show-options -wgv popup-style
$TM show-options -wgv popup-border-style
$TM show-options -wgv window-status-current-style
