//! Global store + installed index. Ported from zshrs's `pkg/store.rs`,
//! retargeted to `$ZTMUX_HOME/pkg/`.
//!
//! Layout (`$ZTMUX_HOME` defaults to `~/.ztmux`, the directory ztmux already
//! keeps its logs and resurrect state in):
//! ```text
//! $ZTMUX_HOME/pkg/
//!   store/  name@version/     # one extracted copy per (name, version)
//!   cache/                    # download scratch
//!   git/                      # git clones
//!   bin/                      # launcher symlinks (future)
//!   installed.toml            # the global install index (source of truth)
//! ```
//! Human-readable `name@version` paths give reproducibility from the index's
//! content hashes without opaque store paths.

use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

use super::{PkgError, PkgResult};

/// Installed-index filename under the store root.
pub(crate) const INSTALLED_FILE: &str = "installed.toml";

/// Resolves and lazily creates the `$ZTMUX_HOME/pkg/...` layout.
pub(crate) struct Store {
    root: PathBuf,
}

impl Store {
    /// Construct a [`Store`] rooted at `$ZTMUX_HOME/pkg/` (default
    /// `~/.ztmux/pkg/`).
    pub(crate) fn user_default() -> PkgResult<Store> {
        let home = match std::env::var_os("ZTMUX_HOME") {
            Some(custom) if !custom.is_empty() => PathBuf::from(custom),
            _ => {
                let h = std::env::var_os("HOME")
                    .ok_or_else(|| PkgError::Other("HOME environment variable not set".into()))?;
                PathBuf::from(h).join(".ztmux")
            }
        };
        Ok(Store {
            root: home.join("pkg"),
        })
    }

    /// Root at an explicit path (tests).
    #[cfg(test)]
    pub(crate) fn at(root: impl Into<PathBuf>) -> Store {
        Store { root: root.into() }
    }

    /// `store/` — extracted packages.
    pub(crate) fn store_dir(&self) -> PathBuf {
        self.root.join("store")
    }
    /// `cache/` — download scratch.
    pub(crate) fn cache_dir(&self) -> PathBuf {
        self.root.join("cache")
    }
    /// `git/` — git clones.
    pub(crate) fn git_dir(&self) -> PathBuf {
        self.root.join("git")
    }
    /// `bin/` — launcher links.
    pub(crate) fn bin_dir(&self) -> PathBuf {
        self.root.join("bin")
    }
    /// `$ZTMUX_HOME/pkg/` root.
    pub(crate) fn root(&self) -> &Path {
        &self.root
    }

    /// Where a package extraction lives: `store/{name}@{version}/`.
    pub(crate) fn package_dir(&self, name: &str, version: &str) -> PathBuf {
        self.store_dir().join(format!("{name}@{version}"))
    }

    /// Create the full directory layout. Idempotent.
    pub(crate) fn ensure_layout(&self) -> PkgResult<()> {
        for d in [
            self.store_dir(),
            self.cache_dir(),
            self.git_dir(),
            self.bin_dir(),
        ] {
            std::fs::create_dir_all(&d)
                .map_err(|e| PkgError::Io(format!("create {}: {e}", d.display())))?;
        }
        Ok(())
    }

    /// Make sure `bin/tmux` is a symlink to the running ztmux, and return the
    /// directory holding it.
    ///
    /// Every published tmux plugin drives the server by shelling out to
    /// `tmux`. Run as-is that reaches whatever `tmux` binary is on `PATH` —
    /// a different program, possibly a different server — so a script plugin
    /// would silently configure the wrong multiplexer, or fail outright on a
    /// machine with no tmux installed. Prepending this directory to a script
    /// plugin's `PATH` makes its `tmux …` calls land in the ztmux server that
    /// is loading it, which is what the plugin means.
    pub(crate) fn ensure_tmux_shim(&self) -> PkgResult<PathBuf> {
        let dir = self.bin_dir();
        std::fs::create_dir_all(&dir)
            .map_err(|e| PkgError::Io(format!("create {}: {e}", dir.display())))?;
        let shim = dir.join("tmux");
        let exe = std::env::current_exe()
            .map_err(|e| PkgError::Io(format!("locate the ztmux binary: {e}")))?;
        // A script rather than a symlink, because the plugin also has to reach
        // the RIGHT server: ztmux adopts `$TMUX` only for a socket in its own
        // default directory, so on a `-S`/`-L` server the plugin's `tmux …`
        // calls would otherwise land on the default one. `znative` exports
        // `ZTMUX_SOCKET` when it runs a plugin; anything else run through this
        // shim behaves like plain ztmux.
        let body = format!(
            "#!/bin/sh\n\
             # Generated by ztmux znative. Regenerated whenever ztmux moves.\n\
             ZTMUX_BIN={}\n\
             if [ -n \"${{ZTMUX_SOCKET:-}}\" ]; then\n\
             \texec \"$ZTMUX_BIN\" -S \"$ZTMUX_SOCKET\" \"$@\"\n\
             fi\n\
             exec \"$ZTMUX_BIN\" \"$@\"\n",
            sh_quote(&exe.to_string_lossy())
        );
        // Rewrite whenever it would change (a rebuild, an upgrade, a different
        // checkout) rather than leaving a stale binary path behind.
        if std::fs::read_to_string(&shim).ok().as_deref() != Some(body.as_str()) {
            let _ = std::fs::remove_file(&shim);
            std::fs::write(&shim, &body)
                .map_err(|e| PkgError::Io(format!("write {}: {e}", shim.display())))?;
            make_executable(&shim);
        }
        Ok(dir)
    }

    /// True if a `name@version` extraction already exists.
    pub(crate) fn has_package(&self, name: &str, version: &str) -> bool {
        self.package_dir(name, version).is_dir()
    }

    /// Copy a staged plugin tree wholesale into `store/{name}@{version}/`,
    /// excluding VCS/build scratch (`.git/`, `target/`) so the store holds
    /// only the loadable plugin. The destination is cleared first for fresh
    /// re-installs. Returns the store path.
    pub(crate) fn install_dir(&self, name: &str, version: &str, src: &Path) -> PkgResult<PathBuf> {
        let dst = self.package_dir(name, version);
        if dst.exists() {
            std::fs::remove_dir_all(&dst)
                .map_err(|e| PkgError::Io(format!("clear {}: {e}", dst.display())))?;
        }
        std::fs::create_dir_all(&dst)?;
        copy_dir_filtered(src, &dst)?;
        Ok(dst)
    }
}

/// The global install index at `$ZTMUX_HOME/pkg/installed.toml` — the single
/// source of truth for what is installed. `znative load` reads it at server
/// start to load every plugin with zero network.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub(crate) struct InstalledIndex {
    /// Schema version.
    pub(crate) version: u32,
    /// One entry per installed plugin, sorted by name for deterministic diffs.
    #[serde(default, rename = "package")]
    pub(crate) packages: Vec<InstalledPlugin>,
}

/// One installed plugin: identity + provenance + everything `znative load`
/// needs to load it without re-resolving.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub(crate) struct InstalledPlugin {
    /// Plugin name (store key `name@version`).
    pub(crate) name: String,
    /// Installed version (`0.0.0` when the plugin declared none).
    pub(crate) version: String,
    /// Provenance: `github:owner/repo`, `git+URL`, or `path+file://DIR`.
    pub(crate) source: String,
    /// `"native"` or `"script"`.
    pub(crate) kind: String,
    /// One-line description from the manifest, when it shipped one.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub(crate) description: String,
    /// SHA-256 of the extracted tree, `sha256-<hex>` (audit / change
    /// detection).
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub(crate) integrity: String,
    /// Native: the cdylib filename inside the store dir (`libfoo.dylib`).
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub(crate) lib: String,
    /// Script: the `*.tmux` files to run, relative to the store dir.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub(crate) run: Vec<String>,
}

impl InstalledIndex {
    /// Empty index stamped with the current schema version.
    pub(crate) fn new() -> InstalledIndex {
        InstalledIndex {
            version: 1,
            packages: Vec::new(),
        }
    }

    /// Load the index from a [`Store`], or an empty index when it does not
    /// exist.
    pub(crate) fn load_from(store: &Store) -> PkgResult<InstalledIndex> {
        let path = store.root().join(INSTALLED_FILE);
        if !path.is_file() {
            return Ok(InstalledIndex::new());
        }
        let s = std::fs::read_to_string(&path)
            .map_err(|e| PkgError::Io(format!("read {}: {e}", path.display())))?;
        toml::from_str::<InstalledIndex>(&s)
            .map_err(|e| PkgError::Other(format!("parse {}: {}", path.display(), e.message())))
    }

    /// Write the index (packages sorted by name) under `store.root()`.
    pub(crate) fn save_to(&mut self, store: &Store) -> PkgResult<()> {
        self.packages.sort_by(|a, b| a.name.cmp(&b.name));
        let path = store.root().join(INSTALLED_FILE);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let body = toml::to_string_pretty(&self)
            .map_err(|e| PkgError::Other(format!("serialize {INSTALLED_FILE}: {e}")))?;
        std::fs::write(
            &path,
            format!("# znative — auto-generated. Do not edit.\n{body}"),
        )
        .map_err(|e| PkgError::Io(format!("write {}: {e}", path.display())))?;
        Ok(())
    }

    /// Find an installed plugin by name.
    pub(crate) fn find(&self, name: &str) -> Option<&InstalledPlugin> {
        self.packages.iter().find(|p| p.name == name)
    }

    /// Insert or replace the entry for `p.name`.
    pub(crate) fn upsert(&mut self, p: InstalledPlugin) {
        if let Some(slot) = self.packages.iter_mut().find(|e| e.name == p.name) {
            *slot = p;
        } else {
            self.packages.push(p);
        }
    }

    /// Remove the entry named `name`; returns it if present.
    pub(crate) fn remove(&mut self, name: &str) -> Option<InstalledPlugin> {
        let idx = self.packages.iter().position(|p| p.name == name)?;
        Some(self.packages.remove(idx))
    }
}

/// Recursively copy `src` into `dst`, skipping `.git/` and `target/` (VCS +
/// Rust build scratch) at any depth. TPM's contract is that a plugin's
/// `*.tmux` file is executed, so those are made executable on the way in —
/// a repo that shipped one without the bit would otherwise fail to load with
/// a permission error rather than anything a user could act on.
fn copy_dir_filtered(src: &Path, dst: &Path) -> PkgResult<()> {
    std::fs::create_dir_all(dst)?;
    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let name = entry.file_name();
        let name_s = name.to_string_lossy().into_owned();
        if name_s == ".git" || name_s == "target" {
            continue;
        }
        let from = entry.path();
        let to = dst.join(&name);
        let ft = entry.file_type()?;
        if ft.is_dir() {
            copy_dir_filtered(&from, &to)?;
        } else if ft.is_symlink() {
            // Copy the resolved file content (plugins rarely ship symlinks; a
            // dangling link in the store would break loads).
            if let Ok(target) = std::fs::read(&from) {
                std::fs::write(&to, target)?;
            }
        } else {
            std::fs::copy(&from, &to)
                .map_err(|e| PkgError::Io(format!("copy {}: {e}", from.display())))?;
        }
        if name_s.ends_with(".tmux") && to.is_file() {
            make_executable(&to);
        }
    }
    Ok(())
}

/// POSIX single-quoting for a path baked into the generated shim.
fn sh_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', r"'\''"))
}

/// Add the owner/group/other execute bits to a file, best effort.
fn make_executable(path: &Path) {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        if let Ok(meta) = std::fs::metadata(path) {
            let mut perms = meta.permissions();
            perms.set_mode(perms.mode() | 0o111);
            let _ = std::fs::set_permissions(path, perms);
        }
    }
    #[cfg(not(unix))]
    let _ = path;
}

/// Scratch-directory helper shared by this module's tests and the manifest
/// tests, which need a throwaway tree to detect a plugin layout in.
#[cfg(test)]
pub(crate) mod tests_support {
    use std::path::PathBuf;

    /// A fresh, empty directory under the system temp dir, unique per process
    /// and call.
    pub(crate) fn tmp_dir(tag: &str) -> PathBuf {
        static N: std::sync::atomic::AtomicU32 = std::sync::atomic::AtomicU32::new(0);
        let n = N.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        let p = std::env::temp_dir().join(format!("znative-{tag}-{}-{n}", std::process::id()));
        let _ = std::fs::remove_dir_all(&p);
        std::fs::create_dir_all(&p).unwrap();
        p
    }
}

#[cfg(test)]
mod tests {
    use super::tests_support::tmp_dir;
    use super::*;

    #[test]
    fn install_dir_skips_git_and_target() {
        let src = tmp_dir("store-src");
        std::fs::write(src.join("a.tmux"), b"#!/bin/sh\n").unwrap();
        std::fs::create_dir_all(src.join(".git")).unwrap();
        std::fs::write(src.join(".git/HEAD"), b"ref").unwrap();
        std::fs::create_dir_all(src.join("target")).unwrap();
        std::fs::write(src.join("target/junk"), b"x").unwrap();
        let store = Store::at(tmp_dir("store-root").join("pkg"));
        store.ensure_layout().unwrap();
        let dst = store.install_dir("a", "0.1.0", &src).unwrap();
        assert!(dst.join("a.tmux").is_file());
        assert!(!dst.join(".git").exists());
        assert!(!dst.join("target").exists());
        let _ = std::fs::remove_dir_all(&src);
        let _ = std::fs::remove_dir_all(store.root());
    }

    /// A `*.tmux` file that arrives without the execute bit still has to run,
    /// because TPM's contract is to execute it directly.
    #[cfg(unix)]
    #[test]
    fn install_dir_makes_tmux_files_executable() {
        use std::os::unix::fs::PermissionsExt;
        let src = tmp_dir("store-exec");
        let f = src.join("plug.tmux");
        std::fs::write(&f, b"#!/bin/sh\n").unwrap();
        std::fs::set_permissions(&f, std::fs::Permissions::from_mode(0o644)).unwrap();
        let store = Store::at(tmp_dir("store-exec-root").join("pkg"));
        store.ensure_layout().unwrap();
        let dst = store.install_dir("plug", "0.1.0", &src).unwrap();
        let mode = std::fs::metadata(dst.join("plug.tmux"))
            .unwrap()
            .permissions()
            .mode();
        assert_eq!(mode & 0o111, 0o111, "mode was {mode:o}");
        let _ = std::fs::remove_dir_all(&src);
        let _ = std::fs::remove_dir_all(store.root());
    }

    #[test]
    fn index_round_trip() {
        let store = Store::at(tmp_dir("store-index").join("pkg"));
        let mut idx = InstalledIndex::new();
        idx.upsert(InstalledPlugin {
            name: "zed".into(),
            version: "1.0.0".into(),
            source: "github:o/zed".into(),
            kind: "script".into(),
            run: vec!["zed.tmux".into()],
            ..Default::default()
        });
        idx.upsert(InstalledPlugin {
            name: "abc".into(),
            version: "0.1.0".into(),
            source: "github:o/abc".into(),
            kind: "native".into(),
            lib: "libabc.dylib".into(),
            ..Default::default()
        });
        idx.save_to(&store).unwrap();
        let back = InstalledIndex::load_from(&store).unwrap();
        assert_eq!(back.packages.len(), 2);
        // Sorted by name: abc before zed.
        assert_eq!(back.packages[0].name, "abc");
        assert_eq!(back.find("zed").unwrap().run, vec!["zed.tmux"]);
        assert_eq!(back.find("abc").unwrap().lib, "libabc.dylib");
        let _ = std::fs::remove_dir_all(store.root());
    }

    /// An `installed.toml` written by a newer ztmux that carries fields this
    /// build does not know must still load — the index is the one file a
    /// user's whole plugin set depends on.
    #[test]
    fn index_tolerates_unknown_fields() {
        let store = Store::at(tmp_dir("store-fwd").join("pkg"));
        store.ensure_layout().unwrap();
        std::fs::write(
            store.root().join(INSTALLED_FILE),
            "version = 1\n[[package]]\nname='p'\nversion='0.1.0'\nsource='github:o/p'\n\
             kind='script'\nrun=['p.tmux']\nfuture_field='x'\n",
        )
        .unwrap();
        let idx = InstalledIndex::load_from(&store).unwrap();
        assert_eq!(idx.find("p").unwrap().run, vec!["p.tmux"]);
        let _ = std::fs::remove_dir_all(store.root());
    }
}
